In [1]:
import pandas as pd
import requests as req
import json

In [2]:
# Read box_office_data.csv which includes ticket price
weekend_boxfinal = pd.read_csv('box_office_data.csv')

In [3]:
weekend_boxfinal.head(12)

,Unnamed: 0,Unnamed: 0.1,Title,Studio,Opening,Date,Director,Budget,imdbID,month,year,ticket_price
0,0,NaN,Avengers: Infinity War,BV,257698183.0,4/27/18,"Anthony Russo, Joe Russo",321000000.0,tt4154756,Apr,2018,NaN
1,1,Jan,Star Wars: The Force Awakens,BV,247966675.0,12/18/15,J.J. Abrams,245000000.0,tt2488496,Dec,2015,$8.43
2,2,Feb,Star Wars: The Last Jedi,BV,220009584.0,12/15/17,Rian Johnson,620181382.0,tt2527336,Dec,2017,$8.97
3,3,Mar,Jurassic World,Uni.,208806270.0,6/12/15,Colin Trevorrow,150000000.0,tt0369610,Jun,2015,$8.43
4,4,Apr,Marvel's The Avengers,BV,207438708.0,5/4/12,NaN,NaN,NaN,May,2012,$7.96
5,5,May,Black Panther,BV,202003951.0,2/16/18,Ryan Coogler,200000000.0,tt1825683,Feb,2018,NaN
6,6,Jun,Avengers: Age of Ultron,BV,191271109.0,5/1/15,Joss Whedon,250000000.0,tt2395427,May,2015,$8.43
7,7,July,Incredibles 2,BV,182687905.0,6/15/18,Brad Bird,200000000.0,tt3606756,Jun,2018,NaN
8,8,Aug,Captain America: Civil War,BV,179139142.0,5/6/16,"Anthony Russo, Joe Russo",250000000.0,tt3498820,May,2016,$8.65
9,9,Sept,Beauty and the Beast (2017),BV,174750616.0,3/17/17,NaN,NaN,NaN,Mar,2017,$8.97
10,10,Oct,Iron Man 3,BV,174144585.0,5/3/13,Shane Black,200000000.0,tt1300854,May,2013,$8.13
11,11,Nov,Harry Potter and the Deathly Hallows Part 2,WB,169189427.0,7/15/11,David Yates,125000000.0,tt1201607,July,2011,$7.93

In [4]:
# Drop the extra index column
weekend_boxfinal = weekend_boxfinal.drop(weekend_boxfinal.columns[[0]], axis=1)

In [5]:
# Add variables
weekend_boxfinal['Actor'] = ''
weekend_boxfinal['Genre'] = ''
weekend_boxfinal['Writer'] = ''
weekend_boxfinal['Ratings'] = ''

In [6]:
# Call OMDB API to add actors, genres, writer, ratings
omdb = 'http://www.omdbapi.com/?apikey=7b298284&t='

In [7]:
# Loop through titles and create title format accepted by OMDB
# Add .head after weekend_box to test/limit API calls - default number is 5
for index, row in weekend_boxfinal.iterrows():
    t = str(row['Title'])
    t = t.replace(":","")
    t = t.replace("'","")
    t = t.replace(' ', '+')
    search = omdb + t
    print (search)
    try:
        results = req.get(search).json()
        if results['Response'] == 'False':
            print("Couldn't find title: ", t)
        else:
            weekend_boxfinal.set_value(index, 'Actor', results['Actors'])
            weekend_boxfinal.set_value(index, 'Genre', results['Genre'])
            weekend_boxfinal.set_value(index, 'Writer', results['Writer'])
            weekend_boxfinal.set_value(index, 'Ratings', results['Ratings'][1])
    except Exception as e:
        print(str(e))
        continue

http://www.omdbapi.com/?apikey=7b298284&t=Avengers+Infinity+War
http://www.omdbapi.com/?apikey=7b298284&t=Star+Wars+The+Force+Awakens
http://www.omdbapi.com/?apikey=7b298284&t=Star+Wars+The+Last+Jedi
http://www.omdbapi.com/?apikey=7b298284&t=Jurassic+World
http://www.omdbapi.com/?apikey=7b298284&t=Marvels+The+Avengers
Couldn't find title:  Marvels+The+Avengers
http://www.omdbapi.com/?apikey=7b298284&t=Black+Panther
http://www.omdbapi.com/?apikey=7b298284&t=Avengers+Age+of+Ultron
http://www.omdbapi.com/?apikey=7b298284&t=Incredibles+2
http://www.omdbapi.com/?apikey=7b298284&t=Captain+America+Civil+War
http://www.omdbapi.com/?apikey=7b298284&t=Beauty+and+the+Beast+(2017)
Couldn't find title:  Beauty+and+the+Beast+(2017)
http://www.omdbapi.com/?apikey=7b298284&t=Iron+Man+3
http://www.omdbapi.com/?apikey=7b298284&t=Harry+Potter+and+the+Deathly+Hallows+Part+2
http://www.omdbapi.com/?apikey=7b298284&t=Batman+v+Superman+Dawn+of+Justice
http://www.omdbapi.com/?apikey=7b298284&t=The+Dark+Knight+Rises
http://www.omdbapi.com/?apikey=7b298284&t=The+Dark+Knight
http://www.omdbapi.com/?apikey=7b298284&t=The+Hunger+Games+Catching+Fire
http://www.omdbapi.com/?apikey=7b298284&t=Rogue+One+A+Star+Wars+Story
http://www.omdbapi.com/?apikey=7b298284&t=The+Hunger+Games
http://www.omdbapi.com/?apikey=7b298284&t=Spider-Man+3
http://www.omdbapi.com/?apikey=7b298284&t=Jurassic+World+Fallen+Kingdom
http://www.omdbapi.com/?apikey=7b298284&t=Furious+7
http://www.omdbapi.com/?apikey=7b298284&t=Guardians+of+the+Galaxy+Vol.+2
http://www.omdbapi.com/?apikey=7b298284&t=The+Twilight+Saga+New+Moon
http://www.omdbapi.com/?apikey=7b298284&t=The+Twilight+Saga+Breaking+Dawn+Part+2
http://www.omdbapi.com/?apikey=7b298284&t=The+Twilight+Saga+Breaking+Dawn+Part+1
list index out of range
http://www.omdbapi.com/?apikey=7b298284&t=Pirates+of+the+Caribbean+Dead+Mans+Chest
Couldn't find title:  Pirates+of+the+Caribbean+Dead+Mans+Chest
http://www.omdbapi.com/?apikey=7b298284&t=Finding+Dory
http://www.omdbapi.com/?apikey=7b298284&t=Suicide+Squad
http://www.omdbapi.com/?apikey=7b298284&t=Deadpool
http://www.omdbapi.com/?apikey=7b298284&t=Iron+Man+2
http://www.omdbapi.com/?apikey=7b298284&t=Deadpool+2
http://www.omdbapi.com/?apikey=7b298284&t=It
http://www.omdbapi.com/?apikey=7b298284&t=Thor+Ragnarok
http://www.omdbapi.com/?apikey=7b298284&t=The+Hunger+Games+Mockingjay+-+Part+1
http://www.omdbapi.com/?apikey=7b298284&t=Shrek+the+Third
http://www.omdbapi.com/?apikey=7b298284&t=Spider-Man+Homecoming
http://www.omdbapi.com/?apikey=7b298284&t=Man+of+Steel
http://www.omdbapi.com/?apikey=7b298284&t=Alice+in+Wonderland+(2010)
Couldn't find title:  Alice+in+Wonderland+(2010)
http://www.omdbapi.com/?apikey=7b298284&t=Minions
http://www.omdbapi.com/?apikey=7b298284&t=Spider-Man
http://www.omdbapi.com/?apikey=7b298284&t=Pirates+of+the+Caribbean+At+Worlds+End
Couldn't find title:  Pirates+of+the+Caribbean+At+Worlds+End
http://www.omdbapi.com/?apikey=7b298284&t=Toy+Story+3
http://www.omdbapi.com/?apikey=7b298284&t=Transformers+Revenge+of+the+Fallen
http://www.omdbapi.com/?apikey=7b298284&t=Star+Wars+Episode+III+-+Revenge+of+the+Sith
http://www.omdbapi.com/?apikey=7b298284&t=Shrek+2
http://www.omdbapi.com/?apikey=7b298284&t=The+Secret+Life+of+Pets
http://www.omdbapi.com/?apikey=7b298284&t=The+Jungle+Book+(2016)
Couldn't find title:  The+Jungle+Book+(2016)
http://www.omdbapi.com/?apikey=7b298284&t=Wonder+Woman
http://www.omdbapi.com/?apikey=7b298284&t=X-Men+The+Last+Stand
http://www.omdbapi.com/?apikey=7b298284&t=Harry+Potter+and+the+Goblet+of+Fire
http://www.omdbapi.com/?apikey=7b298284&t=The+Hunger+Games+Mockingjay+-+Part+2
http://www.omdbapi.com/?apikey=7b298284&t=Indiana+Jones+and+the+Kingdom+of+the+Crystal+Skull
http://www.omdbapi.com/?apikey=7b298284&t=Transformers+Age+of+Extinction
http://www.omdbapi.com/?apikey=7b298284&t=The+Fate+of+the+Furious
http://www.omdbapi.com/?apikey=7b298284&t=Iron+Man
http://www.omdbapi.com/?apikey=7b298284&t=Transformers+Dark+of+the+Moon
http://www.omdbapi.com/?apikey=7b298284&t=Fast+&+Furious+6
http://www.omdbapi.com/?apikey=7b298284&t=Captain+America+The+Winter+Soldier
http://www.omdbapi.com/?apikey=7b298284&t=Guardians+of+the+Galaxy
http://www.omdbapi.com/?apikey=7b298284&t=Justice+League
http://www.omdbapi.com/?apikey=7b298284&t=Harry+Potter+and+the+Prisoner+of+Azkaban
http://www.omdbapi.com/?apikey=7b298284&t=Godzilla+(2014)
Couldn't find title:  Godzilla+(2014)
http://www.omdbapi.com/?apikey=7b298284&t=The+Matrix+Reloaded
http://www.omdbapi.com/?apikey=7b298284&t=The+Amazing+Spider-Man+2
http://www.omdbapi.com/?apikey=7b298284&t=X-Men+Days+of+Future+Past
http://www.omdbapi.com/?apikey=7b298284&t=Inside+Out
http://www.omdbapi.com/?apikey=7b298284&t=Harry+Potter+and+the+Sorcerers+Stone
Couldn't find title:  Harry+Potter+and+the+Sorcerers+Stone
http://www.omdbapi.com/?apikey=7b298284&t=Pirates+of+the+Caribbean+On+Stranger+Tides
http://www.omdbapi.com/?apikey=7b298284&t=American+Sniper
http://www.omdbapi.com/?apikey=7b298284&t=Logan
http://www.omdbapi.com/?apikey=7b298284&t=Harry+Potter+and+the+Chamber+of+Secrets
http://www.omdbapi.com/?apikey=7b298284&t=Spider-Man+2
http://www.omdbapi.com/?apikey=7b298284&t=Fast+Five
http://www.omdbapi.com/?apikey=7b298284&t=The+Hangover+Part+II
http://www.omdbapi.com/?apikey=7b298284&t=Thor+The+Dark+World
http://www.omdbapi.com/?apikey=7b298284&t=X2+X-Men+United
Couldn't find title:  X2+X-Men+United
http://www.omdbapi.com/?apikey=7b298284&t=Fifty+Shades+of+Grey
http://www.omdbapi.com/?apikey=7b298284&t=Doctor+Strange
http://www.omdbapi.com/?apikey=7b298284&t=X-Men+Origins+Wolverine
http://www.omdbapi.com/?apikey=7b298284&t=The+Hobbit+An+Unexpected+Journey
http://www.omdbapi.com/?apikey=7b298284&t=Solo+A+Star+Wars+Story
http://www.omdbapi.com/?apikey=7b298284&t=The+Passion+of+the+Christ
Expecting value: line 1 column 1 (char 0)
http://www.omdbapi.com/?apikey=7b298284&t=Despicable+Me+2
http://www.omdbapi.com/?apikey=7b298284&t=Monsters+University
http://www.omdbapi.com/?apikey=7b298284&t=Star+Wars+Episode+II+-+Attack+of+the+Clones
http://www.omdbapi.com/?apikey=7b298284&t=Oz+The+Great+and+Powerful
http://www.omdbapi.com/?apikey=7b298284&t=Harry+Potter+and+the+Half-Blood+Prince
http://www.omdbapi.com/?apikey=7b298284&t=I+Am+Legend
http://www.omdbapi.com/?apikey=7b298284&t=Harry+Potter+and+the+Order+of+the+Phoenix
http://www.omdbapi.com/?apikey=7b298284&t=The+Da+Vinci+Code
http://www.omdbapi.com/?apikey=7b298284&t=Avatar
http://www.omdbapi.com/?apikey=7b298284&t=Star+Trek
http://www.omdbapi.com/?apikey=7b298284&t=Zootopia
http://www.omdbapi.com/?apikey=7b298284&t=Fantastic+Beasts+and+Where+To+Find+Them
http://www.omdbapi.com/?apikey=7b298284&t=The+Simpsons+Movie
http://www.omdbapi.com/?apikey=7b298284&t=The+Hobbit+The+Desolation+of+Smaug
http://www.omdbapi.com/?apikey=7b298284&t=Austin+Powers+in+Goldmember
http://www.omdbapi.com/?apikey=7b298284&t=The+Lord+of+the+Rings+The+Return+of+the+King
http://www.omdbapi.com/?apikey=7b298284&t=Dawn+of+the+Planet+of+the+Apes
http://www.omdbapi.com/?apikey=7b298284&t=Despicable+Me+3
http://www.omdbapi.com/?apikey=7b298284&t=Fast+and+Furious
list index out of range
http://www.omdbapi.com/?apikey=7b298284&t=300
http://www.omdbapi.com/?apikey=7b298284&t=Shrek+Forever+After
http://www.omdbapi.com/?apikey=7b298284&t=Transformers
http://www.omdbapi.com/?apikey=7b298284&t=The+Incredibles
http://www.omdbapi.com/?apikey=7b298284&t=Spectre
http://www.omdbapi.com/?apikey=7b298284&t=Finding+Nemo
http://www.omdbapi.com/?apikey=7b298284&t=Dr.+Seuss+The+Lorax
Couldn't find title:  Dr.+Seuss+The+Lorax
http://www.omdbapi.com/?apikey=7b298284&t=Star+Trek+Into+Darkness
http://www.omdbapi.com/?apikey=7b298284&t=Twilight
http://www.omdbapi.com/?apikey=7b298284&t=Maleficent
http://www.omdbapi.com/?apikey=7b298284&t=The+Bourne+Ultimatum
http://www.omdbapi.com/?apikey=7b298284&t=Pitch+Perfect+2
http://www.omdbapi.com/?apikey=7b298284&t=The+LEGO+Movie
http://www.omdbapi.com/?apikey=7b298284&t=The+Day+After+Tomorrow
http://www.omdbapi.com/?apikey=7b298284&t=Planet+of+the+Apes+(2001)
Couldn't find title:  Planet+of+the+Apes+(2001)
http://www.omdbapi.com/?apikey=7b298284&t=The+Mummy+Returns
http://www.omdbapi.com/?apikey=7b298284&t=Up

http://www.omdbapi.com/?apikey=7b298284&t=Ice+Age+The+Meltdown
http://www.omdbapi.com/?apikey=7b298284&t=Bruce+Almighty
http://www.omdbapi.com/?apikey=7b298284&t=Cinderella+(2015)
Couldn't find title:  Cinderella+(2015)
http://www.omdbapi.com/?apikey=7b298284&t=Quantum+of+Solace
http://www.omdbapi.com/?apikey=7b298284&t=Rush+Hour+2
http://www.omdbapi.com/?apikey=7b298284&t=Frozen
http://www.omdbapi.com/?apikey=7b298284&t=World+War+Z
http://www.omdbapi.com/?apikey=7b298284&t=Brave
http://www.omdbapi.com/?apikey=7b298284&t=Cars+2
http://www.omdbapi.com/?apikey=7b298284&t=X-Men+Apocalypse
http://www.omdbapi.com/?apikey=7b298284&t=Thor
http://www.omdbapi.com/?apikey=7b298284&t=Teenage+Mutant+Ninja+Turtles+(2014)
Couldn't find title:  Teenage+Mutant+Ninja+Turtles+(2014)
http://www.omdbapi.com/?apikey=7b298284&t=The+Chronicles+of+Narnia+The+Lion,+the+Witch+and+the+Wardrobe
http://www.omdbapi.com/?apikey=7b298284&t=2012
http://www.omdbapi.com/?apikey=7b298284&t=Captain+America+The+First+Avenger
http://www.omdbapi.com/?apikey=7b298284&t=War+of+the+Worlds
http://www.omdbapi.com/?apikey=7b298284&t=The+Twilight+Saga+Eclipse
http://www.omdbapi.com/?apikey=7b298284&t=Madagascar+Escape+2+Africa
http://www.omdbapi.com/?apikey=7b298284&t=WALL-E
http://www.omdbapi.com/?apikey=7b298284&t=Pirates+of+the+Caribbean+Dead+Men+Tell+No+Tales
http://www.omdbapi.com/?apikey=7b298284&t=Inception
http://www.omdbapi.com/?apikey=7b298284&t=Hancock
http://www.omdbapi.com/?apikey=7b298284&t=Monsters,+Inc.
http://www.omdbapi.com/?apikey=7b298284&t=Sherlock+Holmes
http://www.omdbapi.com/?apikey=7b298284&t=Hulk
http://www.omdbapi.com/?apikey=7b298284&t=The+Lord+of+the+Rings+The+Two+Towers
http://www.omdbapi.com/?apikey=7b298284&t=The+Amazing+Spider-Man
http://www.omdbapi.com/?apikey=7b298284&t=Clash+of+the+Titans+(2010)
Couldn't find title:  Clash+of+the+Titans+(2010)
http://www.omdbapi.com/?apikey=7b298284&t=Kong+Skull+Island
http://www.omdbapi.com/?apikey=7b298284&t=Madagascar+3+Europes+Most+Wanted
Couldn't find title:  Madagascar+3+Europes+Most+Wanted
http://www.omdbapi.com/?apikey=7b298284&t=Kung+Fu+Panda
http://www.omdbapi.com/?apikey=7b298284&t=Straight+Outta+Compton
http://www.omdbapi.com/?apikey=7b298284&t=Cars
http://www.omdbapi.com/?apikey=7b298284&t=Signs
http://www.omdbapi.com/?apikey=7b298284&t=Monsters+Vs.+Aliens
Couldn't find title:  Monsters+Vs.+Aliens
http://www.omdbapi.com/?apikey=7b298284&t=Star+Trek+Beyond
http://www.omdbapi.com/?apikey=7b298284&t=Jason+Bourne
http://www.omdbapi.com/?apikey=7b298284&t=Pearl+Harbor
http://www.omdbapi.com/?apikey=7b298284&t=Fantastic+Four+Rise+of+the+Silver+Surfer
Couldn't find title:  Fantastic+Four+Rise+of+the+Silver+Surfer
http://www.omdbapi.com/?apikey=7b298284&t=Hannibal
http://www.omdbapi.com/?apikey=7b298284&t=Mission+Impossible+II
http://www.omdbapi.com/?apikey=7b298284&t=Ant-Man
http://www.omdbapi.com/?apikey=7b298284&t=22+Jump+Street
http://www.omdbapi.com/?apikey=7b298284&t=Sex+and+the+City
http://www.omdbapi.com/?apikey=7b298284&t=Moana
http://www.omdbapi.com/?apikey=7b298284&t=Despicable+Me
http://www.omdbapi.com/?apikey=7b298284&t=War+for+the+Planet+of+the+Apes
http://www.omdbapi.com/?apikey=7b298284&t=Snow+White+and+the+Huntsman
http://www.omdbapi.com/?apikey=7b298284&t=Big+Hero+6
http://www.omdbapi.com/?apikey=7b298284&t=Charlie+and+the+Chocolate+Factory
http://www.omdbapi.com/?apikey=7b298284&t=Fantastic+Four+(2005)
Expecting value: line 1 column 1 (char 0)
http://www.omdbapi.com/?apikey=7b298284&t=Gravity
http://www.omdbapi.com/?apikey=7b298284&t=The+Karate+Kid
http://www.omdbapi.com/?apikey=7b298284&t=Mission+Impossible+-+Rogue+Nation
http://www.omdbapi.com/?apikey=7b298284&t=The+Incredible+Hulk
http://www.omdbapi.com/?apikey=7b298284&t=The+SpongeBob+Movie+Sponge+Out+of+Water
http://www.omdbapi.com/?apikey=7b298284&t=Watchmen
http://www.omdbapi.com/?apikey=7b298284&t=X-Men+First+Class
http://www.omdbapi.com/?apikey=7b298284&t=How+the+Grinch+Stole+Christmas
http://www.omdbapi.com/?apikey=7b298284&t=The+Chronicles+of+Narnia+Prince+Caspian
http://www.omdbapi.com/?apikey=7b298284&t=Rise+of+the+Planet+of+the+Apes
http://www.omdbapi.com/?apikey=7b298284&t=The+Hobbit+The+Battle+of+the+Five+Armies
http://www.omdbapi.com/?apikey=7b298284&t=G.I.+Joe+The+Rise+of+Cobra
http://www.omdbapi.com/?apikey=7b298284&t=Divergent
http://www.omdbapi.com/?apikey=7b298284&t=MIB+3
list index out of range
http://www.omdbapi.com/?apikey=7b298284&t=San+Andreas
http://www.omdbapi.com/?apikey=7b298284&t=X-Men
http://www.omdbapi.com/?apikey=7b298284&t=Ted
http://www.omdbapi.com/?apikey=7b298284&t=The+Martian
http://www.omdbapi.com/?apikey=7b298284&t=Night+at+the+Museum+Battle+of+the+Smithsonian
http://www.omdbapi.com/?apikey=7b298284&t=Scooby-Doo
http://www.omdbapi.com/?apikey=7b298284&t=Cars+3
http://www.omdbapi.com/?apikey=7b298284&t=Green+Lantern
http://www.omdbapi.com/?apikey=7b298284&t=The+Wolverine
http://www.omdbapi.com/?apikey=7b298284&t=The+LEGO+Batman+Movie
http://www.omdbapi.com/?apikey=7b298284&t=Paranormal+Activity+3
http://www.omdbapi.com/?apikey=7b298284&t=Superman+Returns
http://www.omdbapi.com/?apikey=7b298284&t=The+Bourne+Supremacy
http://www.omdbapi.com/?apikey=7b298284&t=The+Divergent+Series+Insurgent
Couldn't find title:  The+Divergent+Series+Insurgent
http://www.omdbapi.com/?apikey=7b298284&t=I,+Robot
http://www.omdbapi.com/?apikey=7b298284&t=Men+in+Black+II
http://www.omdbapi.com/?apikey=7b298284&t=Home+(2015)
Couldn't find title:  Home+(2015)
http://www.omdbapi.com/?apikey=7b298284&t=Van+Helsing
http://www.omdbapi.com/?apikey=7b298284&t=8+Mile
http://www.omdbapi.com/?apikey=7b298284&t=Prometheus
http://www.omdbapi.com/?apikey=7b298284&t=Wanted
http://www.omdbapi.com/?apikey=7b298284&t=Coco
http://www.omdbapi.com/?apikey=7b298284&t=Jurassic+Park+III
http://www.omdbapi.com/?apikey=7b298284&t=The+Village
http://www.omdbapi.com/?apikey=7b298284&t=Dunkirk
http://www.omdbapi.com/?apikey=7b298284&t=2+Fast+2+Furious
http://www.omdbapi.com/?apikey=7b298284&t=Jackass+3-D
Couldn't find title:  Jackass+3-D
http://www.omdbapi.com/?apikey=7b298284&t=Mr.+&+Mrs.+Smith
http://www.omdbapi.com/?apikey=7b298284&t=A+Quiet+Place
http://www.omdbapi.com/?apikey=7b298284&t=The+Boss+Baby
http://www.omdbapi.com/?apikey=7b298284&t=King+Kong
http://www.omdbapi.com/?apikey=7b298284&t=The+Great+Gatsby+(2013)
Couldn't find title:  The+Great+Gatsby+(2013)

In [9]:
len(weekend_boxfinal)

215

In [10]:
weekend_boxfinal.head(12)

,Unnamed: 0.1,Title,Studio,Opening,Date,Director,Budget,imdbID,month,year,ticket_price,Actor,Genre,Writer,Ratings
0,NaN,Avengers: Infinity War,BV,257698183.0,4/27/18,"Anthony Russo, Joe Russo",321000000.0,tt4154756,Apr,2018,NaN,"Robert Downey Jr., Chris Hemsworth, Mark Ruffa...","Action, Adventure, Fantasy","Christopher Markus (screenplay by), Stephen Mc...","{'Source': 'Rotten Tomatoes', 'Value': '83%'}"
1,Jan,Star Wars: The Force Awakens,BV,247966675.0,12/18/15,J.J. Abrams,245000000.0,tt2488496,Dec,2015,$8.43,"Harrison Ford, Mark Hamill, Carrie Fisher, Ada...","Action, Adventure, Fantasy","Lawrence Kasdan, J.J. Abrams, Michael Arndt, G...","{'Source': 'Rotten Tomatoes', 'Value': '93%'}"
2,Feb,Star Wars: The Last Jedi,BV,220009584.0,12/15/17,Rian Johnson,620181382.0,tt2527336,Dec,2017,$8.97,"Mark Hamill, Carrie Fisher, Adam Driver, Daisy...","Action, Adventure, Fantasy","Rian Johnson, George Lucas (based on character...","{'Source': 'Rotten Tomatoes', 'Value': '91%'}"
3,Mar,Jurassic World,Uni.,208806270.0,6/12/15,Colin Trevorrow,150000000.0,tt0369610,Jun,2015,$8.43,"Chris Pratt, Bryce Dallas Howard, Irrfan Khan,...","Action, Adventure, Sci-Fi","Rick Jaffa (screenplay by), Amanda Silver (scr...","{'Source': 'Rotten Tomatoes', 'Value': '71%'}"
4,Apr,Marvel's The Avengers,BV,207438708.0,5/4/12,NaN,NaN,NaN,May,2012,$7.96,,,,
5,May,Black Panther,BV,202003951.0,2/16/18,Ryan Coogler,200000000.0,tt1825683,Feb,2018,NaN,"Chadwick Boseman, Michael B. Jordan, Lupita Ny...","Action, Adventure, Sci-Fi","Ryan Coogler, Joe Robert Cole, Stan Lee (based...","{'Source': 'Rotten Tomatoes', 'Value': '97%'}"
6,Jun,Avengers: Age of Ultron,BV,191271109.0,5/1/15,Joss Whedon,250000000.0,tt2395427,May,2015,$8.43,"Robert Downey Jr., Chris Hemsworth, Mark Ruffa...","Action, Adventure, Sci-Fi","Joss Whedon, Stan Lee (based on the Marvel com...","{'Source': 'Rotten Tomatoes', 'Value': '75%'}"
7,July,Incredibles 2,BV,182687905.0,6/15/18,Brad Bird,200000000.0,tt3606756,Jun,2018,NaN,"Craig T. Nelson, Holly Hunter, Sarah Vowell, H...","Animation, Action, Adventure",Brad Bird,"{'Source': 'Rotten Tomatoes', 'Value': '94%'}"
8,Aug,Captain America: Civil War,BV,179139142.0,5/6/16,"Anthony Russo, Joe Russo",250000000.0,tt3498820,May,2016,$8.65,"Chris Evans, Robert Downey Jr., Scarlett Johan...","Action, Adventure, Sci-Fi","Christopher Markus (screenplay by), Stephen Mc...","{'Source': 'Rotten Tomatoes', 'Value': '91%'}"
9,Sept,Beauty and the Beast (2017),BV,174750616.0,3/17/17,NaN,NaN,NaN,Mar,2017,$8.97,,,,
10,Oct,Iron Man 3,BV,174144585.0,5/3/13,Shane Black,200000000.0,tt1300854,May,2013,$8.13,"Robert Downey Jr., Gwyneth Paltrow, Don Cheadl...","Action, Adventure, Sci-Fi","Drew Pearce (screenplay by), Shane Black (scre...","{'Source': 'Rotten Tomatoes', 'Value': '80%'}"
11,Nov,Harry Potter and the Deathly Hallows Part 2,WB,169189427.0,7/15/11,David Yates,125000000.0,tt1201607,July,2011,$7.93,"Ralph Fiennes, Michael Gambon, Alan Rickman, D...","Adventure, Drama, Fantasy","Steve Kloves (screenplay), J.K. Rowling (novel)","{'Source': 'Rotten Tomatoes', 'Value': '96%'}"

In [12]:
for index, row in weekend_boxfinal.iterrows():
    try:
        rating = row['Ratings']
        rating = rating['Value']
        rating = rating.replace('%','')
        rating = float(rating)
        rating = rating/100
    except:
        continue    
    weekend_boxfinal.set_value(index, 'Ratings', rating)

In [13]:
weekend_boxfinal.rename(columns={'month': 'Month', 'year': 'Year', 'ticket_price': 'Ticket_Price'}, inplace=True)

In [14]:
weekend_boxfinal.head(12)

,Unnamed: 0.1,Title,Studio,Opening,Date,Director,Budget,imdbID,Month,Year,Ticket_Price,Actor,Genre,Writer,Ratings
0,NaN,Avengers: Infinity War,BV,257698183.0,4/27/18,"Anthony Russo, Joe Russo",321000000.0,tt4154756,Apr,2018,NaN,"Robert Downey Jr., Chris Hemsworth, Mark Ruffa...","Action, Adventure, Fantasy","Christopher Markus (screenplay by), Stephen Mc...",0.83
1,Jan,Star Wars: The Force Awakens,BV,247966675.0,12/18/15,J.J. Abrams,245000000.0,tt2488496,Dec,2015,$8.43,"Harrison Ford, Mark Hamill, Carrie Fisher, Ada...","Action, Adventure, Fantasy","Lawrence Kasdan, J.J. Abrams, Michael Arndt, G...",0.93
2,Feb,Star Wars: The Last Jedi,BV,220009584.0,12/15/17,Rian Johnson,620181382.0,tt2527336,Dec,2017,$8.97,"Mark Hamill, Carrie Fisher, Adam Driver, Daisy...","Action, Adventure, Fantasy","Rian Johnson, George Lucas (based on character...",0.91
3,Mar,Jurassic World,Uni.,208806270.0,6/12/15,Colin Trevorrow,150000000.0,tt0369610,Jun,2015,$8.43,"Chris Pratt, Bryce Dallas Howard, Irrfan Khan,...","Action, Adventure, Sci-Fi","Rick Jaffa (screenplay by), Amanda Silver (scr...",0.71
4,Apr,Marvel's The Avengers,BV,207438708.0,5/4/12,NaN,NaN,NaN,May,2012,$7.96,,,,
5,May,Black Panther,BV,202003951.0,2/16/18,Ryan Coogler,200000000.0,tt1825683,Feb,2018,NaN,"Chadwick Boseman, Michael B. Jordan, Lupita Ny...","Action, Adventure, Sci-Fi","Ryan Coogler, Joe Robert Cole, Stan Lee (based...",0.97
6,Jun,Avengers: Age of Ultron,BV,191271109.0,5/1/15,Joss Whedon,250000000.0,tt2395427,May,2015,$8.43,"Robert Downey Jr., Chris Hemsworth, Mark Ruffa...","Action, Adventure, Sci-Fi","Joss Whedon, Stan Lee (based on the Marvel com...",0.75
7,July,Incredibles 2,BV,182687905.0,6/15/18,Brad Bird,200000000.0,tt3606756,Jun,2018,NaN,"Craig T. Nelson, Holly Hunter, Sarah Vowell, H...","Animation, Action, Adventure",Brad Bird,0.94
8,Aug,Captain America: Civil War,BV,179139142.0,5/6/16,"Anthony Russo, Joe Russo",250000000.0,tt3498820,May,2016,$8.65,"Chris Evans, Robert Downey Jr., Scarlett Johan...","Action, Adventure, Sci-Fi","Christopher Markus (screenplay by), Stephen Mc...",0.91
9,Sept,Beauty and the Beast (2017),BV,174750616.0,3/17/17,NaN,NaN,NaN,Mar,2017,$8.97,,,,
10,Oct,Iron Man 3,BV,174144585.0,5/3/13,Shane Black,200000000.0,tt1300854,May,2013,$8.13,"Robert Downey Jr., Gwyneth Paltrow, Don Cheadl...","Action, Adventure, Sci-Fi","Drew Pearce (screenplay by), Shane Black (scre...",0.8
11,Nov,Harry Potter and the Deathly Hallows Part 2,WB,169189427.0,7/15/11,David Yates,125000000.0,tt1201607,July,2011,$7.93,"Ralph Fiennes, Michael Gambon, Alan Rickman, D...","Adventure, Drama, Fantasy","Steve Kloves (screenplay), J.K. Rowling (novel)",0.96

In [15]:
weekend_boxfinal.to_csv('finalDataset.csv')