In [2]:
import pandas as pd
import requests as req
import json
from bs4 import BeautifulSoup

In [3]:
weekend_box_1 = pd.read_html('http://www.boxofficemojo.com/alltime/weekends/?pagenum=m50&sort=opengross&p=.htm&order=DESC')[0]
weekend_box_2 = pd.read_html('http://www.boxofficemojo.com/alltime/weekends/?pagenum=m4050&sort=opengross&p=.htm&order=DESC')[0]
weekend_box_3 = pd.read_html('http://www.boxofficemojo.com/alltime/weekends/?pagenum=m3040&sort=opengross&p=.htm&order=DESC')[0]
weekend_box_4 = pd.read_html('http://www.boxofficemojo.com/alltime/weekends/?pagenum=m2530&sort=opengross&p=.htm&order=DESC')[0]
weekend_box_5 = pd.read_html('http://www.boxofficemojo.com/alltime/weekends/?pagenum=m2025&sort=opengross&p=.htm&order=DESC')[0]
weekend_box_6 = pd.read_html('http://www.boxofficemojo.com/alltime/weekends/?pagenum=m1520&sort=opengross&p=.htm&order=DESC')[0]
weekend_box_7 = pd.read_html('http://www.boxofficemojo.com/alltime/weekends/?pagenum=m1015&sort=opengross&p=.htm&order=DESC')[0]

In [4]:
weekend_box_7

,0,1,2,3,4,5,6,7,8,9,...,6271,6272,6273,6274,6275,6276,6277,6278,6279,6280
0,> ALL TIME BOX OFFICE Adjuster: Actuals Est...,> ALL TIME BOX OFFICE,Adjuster: Actuals Est. Tckts for(i=2018; i>...,Adjuster: Actuals Est. Tckts for(i=2018; i>...,NaN,OPENING WEEKENDS $50+ M $40-50m $30-40m $25-30...,Rank,Title (click to view),Studio,Opening*,...,Lawless,Wein.,"$10,001,982",26.7%,2888.0,"$3,463","$37,400,127",8/29/2012,googletag.cmd.push(function() { googletag.def...,NaN
1,> ALL TIME BOX OFFICE,Adjuster: Actuals Est. Tckts for(i=2018; i>...,Adjuster: Actuals Est. Tckts for(i=2018; i>...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Adjuster: Actuals Est. Tckts for(i=2018; i>...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,OPENING WEEKENDS $50+ M $40-50m $30-40m $25-30...,Rank,Title (click to view),Studio,Opening*,% of Total,Theaters,Avg.,Total Gross^,Date**,...,"$3,463","$37,400,127",8/29/2012,googletag.cmd.push(function() { googletag.def...,NaN,NaN,NaN,NaN,NaN,NaN
5,Rank,Title (click to view),Studio,Opening*,% of Total,Theaters,Avg.,Total Gross^,Date**,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1312,Priest,SGem,"$14,953,664",51.3%,2864,"$5,221","$29,136,626",5/13/2011,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1313,Tag,WB (NL),"$14,947,396",36.6%,3382,"$4,420","$40,887,808",6/15/2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1314,Dangerous Minds,BV,"$14,931,503",17.6%,1348,"$11,076","$84,919,401",8/11/1995,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1315,The Boy Next Door,Uni.,"$14,910,105",42.1%,2602,"$5,730","$35,423,380",1/23/2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1316,Harold and Kumar Escape from Guantanamo Bay,WB (NL),"$14,908,404",39.1%,2510,"$5,940","$38,108,728",4/25/2008,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1317,Surrogates,BV,"$14,902,692",38.6%,2951,"$5,050","$38,577,772",9/25/2009,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1318,Passengers (2016),Sony,"$14,869,736",14.9%,3478,"$4,275","$100,014,699",12/21/2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1319,Inferno,Sony,"$14,860,425",43.3%,3576,"$4,156","$34,343,574",10/28/2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1320,Seven Pounds,Sony,"$14,851,136",21.2%,2758,"$5,385","$69,951,824",12/19/2008,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1321,Pitch Perfect,Uni.,"$14,846,830",22.8%,2770,"$5,360","$65,001,093",10/5/2012,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1322,American Assassin,LGF,"$14,846,778",41.0%,3154,"$4,707","$36,249,674",9/15/2017,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1323,A Time to Kill,WB,"$14,823,159",13.6%,2123,"$6,982","$108,766,007",7/24/1996,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1324,Miracles from Heaven,TriS,"$14,812,393",24.0%,3047,"$4,861","$61,705,123",3/16/2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1325,Source Code,Sum.,"$14,812,094",27.1%,2961,"$5,002","$54,712,227",4/1/2011,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1326,The Prestige,BV,"$14,801,808",27.9%,2281,"$6,489","$53,089,891",10/20/2006,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1327,Australia,Fox,"$14,800,723",29.9%,2642,"$5,602","$49,554,002",11/26/2008,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1328,The Rite,WB (NL),"$14,789,393",44.8%,2985,"$4,955","$33,047,633",1/28/2011,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1329,Money Monster,TriS,"$14,788,157",36.1%,3104,"$4,764","$41,012,075",5/13/2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1330,Queen of the Damned,WB,"$14,757,535",48.6%,2511,"$5,877","$30,336,800",2/22/2002,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1331,Made of Honor,Sony,"$14,756,850",32.1%,2729,"$5,407","$46,012,734",5/2/2008,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1332,The Cabin in the Woods,LGF,"$14,743,614",35.0%,2811,"$5,245","$42,073,277",4/13/2012,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,1333,The Messengers,SGem,"$14,713,321",41.6%,2528,"$5,820","$35,374,833",2/2/2007,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1334,White Men Can't Jump,Fox,"$14,711,124",19.3%,1923,"$7,650","$76,253,806",3/27/1992,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1335,Overboard (2018),PNT,"$14,711,101",29.3%,1623,"$9,064","$50,188,946",5/4/2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
673,1979,Problem Child,Uni.,"$10,026,900",18.8%,1714,"$5,850","$53,470,891",7/27/1990,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
674,1980,The Reaping,WB,"$10,025,203",39.9%,2603,"$3,851","$25,126,214",4/5/2007,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
675,1981,The Last Mimzy,NL,"$10,024,819",46.7%,3017,"$3,322","$21,471,047",3/23/2007,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
676,1982,Valentine,WB,"$10,024,648",49.2%,2310,"$4,339","$20,384,136",2/2/2001,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
677,1983,Accepted,Uni.,"$10,023,835",27.6%,2914,"$3,439","$36,323,505",8/18/2006,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
678,1984,Boyz N the Hood,Col.,"$10,023,462",17.4%,829,"$12,091","$57,504,069",7/12/1991,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
679,1985,The Untouchables,Par.,"$10,023,094",13.1%,1012,"$9,904","$76,270,454",6/5/1987,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
680,1986,The X-Files: I Want to Believe,Fox,"$10,021,753",47.8%,3185,"$3,147","$20,982,478",7/25/2008,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
681,1987,Fat Albert,Fox,"$10,021,510",20.8%,2674,"$3,747","$48,116,322",12/25/2004,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
682,1988,Conan the Barbarian (2011),LGF,"$10,021,215",47.1%,3015,"$3,324","$21,295,021",8/19/2011,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
683,1989,Seven Years in Tibet,Sony,"$10,020,378",26.4%,2103,"$4,764","$37,957,682",10/10/1997,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
684,1990,Dragon: The Bruce Lee Story,Uni.,"$10,019,970",28.5%,1887,"$5,310","$35,113,743",5/7/1993,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
685,1991,Mystery Men,Uni.,"$10,017,865",33.7%,2136,"$4,690","$29,762,011",8/6/1999,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
686,1992,Sea of Love,Uni.,"$10,017,840",17.1%,1246,"$8,040","$58,571,513",9/15/1989,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
687,1993,In Her Shoes,Fox,"$10,017,575",30.5%,2808,"$3,567","$32,880,591",10/7/2005,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
688,1994,Sleepwalkers,Col.,"$10,017,354",32.8%,1864,"$5,374","$30,524,763",4/10/1992,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
689,1995,Mr. Brooks,MGM,"$10,017,067",35.1%,2453,"$4,084","$28,549,298",6/1/2007,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
690,1996,Kidnap (2017),Aviron,"$10,016,323",32.6%,2378,"$4,212","$30,718,107",8/4/2017,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
691,1997,Rent,SonR,"$10,016,021",34.4%,2433,"$4,116","$29,077,547",11/23/2005,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
692,1998,Daylight,Uni.,"$10,015,875",30.3%,2175,"$4,605","$33,023,469",12/6/1996,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
693,1999,Final Destination,NL,"$10,015,822",18.8%,2587,"$3,871","$53,331,147",3/17/2000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
694,2000,Rush (2013),Uni.,"$10,014,920",37.2%,2297,"$4,360","$26,947,624",9/27/2013,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
695,2001,The American President,Sony,"$10,014,558",16.7%,1508,"$6,640","$60,079,496",11/17/1995,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
696,2002,Fame (2009),MGM,"$10,011,682",44.6%,3096,"$3,234","$22,455,510",9/25/2009,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
697,2003,Someone Like You,Fox,"$10,010,600",36.6%,2345,"$4,268","$27,343,067",3/30/2001,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
698,2004,All About the Benjamins,NL,"$10,007,291",38.6%,1505,"$6,649","$25,916,319",3/8/2002,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
699,2005,The Black Dahlia,Uni.,"$10,005,895",44.4%,2226,"$4,495","$22,545,080",9/15/2006,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
700,2006,The Best of Me,Rela.,"$10,003,827",37.4%,2936,"$3,407","$26,766,213",10/17/2014,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
701,2007,Lawless,Wein.,"$10,001,982",26.7%,2888,"$3,463","$37,400,127",8/29/2012,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
weekend_box_1 = weekend_box_1.iloc[5:]
weekend_box_2 = weekend_box_2.iloc[5:]
weekend_box_3 = weekend_box_3.iloc[5:]
weekend_box_4 = weekend_box_4.iloc[5:]
weekend_box_5 = weekend_box_5.iloc[5:]
weekend_box_6 = weekend_box_6.iloc[5:]
weekend_box_7 = weekend_box_7.iloc[5:]

In [6]:
weekend_box_1 = weekend_box_1[[0,1,2,3,4,5,6,7,8]]
weekend_box_2 = weekend_box_2[[0,1,2,3,4,5,6,7,8]]
weekend_box_3 = weekend_box_3[[0,1,2,3,4,5,6,7,8]]
weekend_box_4 = weekend_box_4[[0,1,2,3,4,5,6,7,8]]
weekend_box_5 = weekend_box_5[[0,1,2,3,4,5,6,7,8]]
weekend_box_6 = weekend_box_6[[0,1,2,3,4,5,6,7,8]]
weekend_box_7 = weekend_box_7[[0,1,2,3,4,5,6,7,8]]

In [7]:
weekend_box_7.head()

,0,1,2,3,4,5,6,7,8
5,Rank,Title (click to view),Studio,Opening*,% of Total,Theaters,Avg.,Total Gross^,Date**
6,1312,Priest,SGem,"$14,953,664",51.3%,2864,"$5,221","$29,136,626",5/13/2011
7,1313,Tag,WB (NL),"$14,947,396",36.6%,3382,"$4,420","$40,887,808",6/15/2018
8,1314,Dangerous Minds,BV,"$14,931,503",17.6%,1348,"$11,076","$84,919,401",8/11/1995
9,1315,The Boy Next Door,Uni.,"$14,910,105",42.1%,2602,"$5,730","$35,423,380",1/23/2015

In [8]:
weekend_box_1.columns = weekend_box_1.iloc[0]
weekend_box_2.columns = weekend_box_2.iloc[0]
weekend_box_3.columns = weekend_box_3.iloc[0]
weekend_box_4.columns = weekend_box_4.iloc[0]
weekend_box_5.columns = weekend_box_5.iloc[0]
weekend_box_6.columns = weekend_box_6.iloc[0]
weekend_box_7.columns = weekend_box_7.iloc[0]

In [9]:
weekend_box_1 = weekend_box_1.iloc[1:]
weekend_box_2 = weekend_box_2.iloc[1:]
weekend_box_3 = weekend_box_3.iloc[1:]
weekend_box_4 = weekend_box_4.iloc[1:]
weekend_box_5 = weekend_box_5.iloc[1:]
weekend_box_6 = weekend_box_6.iloc[1:]
weekend_box_7 = weekend_box_7.iloc[1:]

In [10]:
weekend_box_1 = weekend_box_1[['Title (click to view)', 'Studio', 'Opening*', 'Date**']]
weekend_box_2 = weekend_box_2[['Title (click to view)', 'Studio', 'Opening*', 'Date**']]
weekend_box_3 = weekend_box_3[['Title (click to view)', 'Studio', 'Opening*', 'Date**']]
weekend_box_4 = weekend_box_4[['Title (click to view)', 'Studio', 'Opening*', 'Date**']]
weekend_box_5 = weekend_box_5[['Title (click to view)', 'Studio', 'Opening*', 'Date**']]
weekend_box_6 = weekend_box_6[['Title (click to view)', 'Studio', 'Opening*', 'Date**']]
weekend_box_7 = weekend_box_7[['Title (click to view)', 'Studio', 'Opening*', 'Date**']]

In [11]:
weekend_box_1.columns = ['Title', 'Studio', 'Opening', 'Date']
weekend_box_2.columns = ['Title', 'Studio', 'Opening', 'Date']
weekend_box_3.columns = ['Title', 'Studio', 'Opening', 'Date']
weekend_box_4.columns = ['Title', 'Studio', 'Opening', 'Date']
weekend_box_5.columns = ['Title', 'Studio', 'Opening', 'Date']
weekend_box_6.columns = ['Title', 'Studio', 'Opening', 'Date']
weekend_box_7.columns = ['Title', 'Studio', 'Opening', 'Date']

In [12]:
frames = [weekend_box_1, weekend_box_2, weekend_box_3, weekend_box_4, weekend_box_5, weekend_box_6, weekend_box_7]

weekend_box = pd.concat(frames)

In [13]:
weekend_box = weekend_box[:-1]

In [14]:
weekend_box.head()

                           Title Studio       Opening        Date
6         Avengers: Infinity War     BV  $257,698,183   4/27/2018
7   Star Wars: The Force Awakens     BV  $247,966,675  12/18/2015
8       Star Wars: The Last Jedi     BV  $220,009,584  12/15/2017
9                 Jurassic World   Uni.  $208,806,270   6/12/2015
10         Marvel's The Avengers     BV  $207,438,708    5/4/2012

In [15]:
weekend_box['Director'] = ''
weekend_box['Budget'] = ''
weekend_box['imdbID'] = ''
weekend_box['month'] = ''
weekend_box['year'] = ''
weekend_box['Actor'] = ''
weekend_box['Genre'] = ''
weekend_box['Writer'] = ''

In [16]:
weekend_box

,Title,Studio,Opening,Date,Director,Budget,imdbID,month,year,Actor,Genre,Writer
6,Avengers: Infinity War,BV,"$257,698,183",4/27/2018,,,,,,,,
7,Star Wars: The Force Awakens,BV,"$247,966,675",12/18/2015,,,,,,,,
8,Star Wars: The Last Jedi,BV,"$220,009,584",12/15/2017,,,,,,,,
9,Jurassic World,Uni.,"$208,806,270",6/12/2015,,,,,,,,
10,Marvel's The Avengers,BV,"$207,438,708",5/4/2012,,,,,,,,
11,Black Panther,BV,"$202,003,951",2/16/2018,,,,,,,,
12,Avengers: Age of Ultron,BV,"$191,271,109",5/1/2015,,,,,,,,
13,Incredibles 2,BV,"$182,687,905",6/15/2018,,,,,,,,
14,Captain America: Civil War,BV,"$179,139,142",5/6/2016,,,,,,,,
15,Beauty and the Beast (2017),BV,"$174,750,616",3/17/2017,,,,,,,,
16,Iron Man 3,BV,"$174,144,585",5/3/2013,,,,,,,,
17,Harry Potter and the Deathly Hallows Part 2,WB,"$169,189,427",7/15/2011,,,,,,,,
18,Batman v Superman: Dawn of Justice,WB,"$166,007,347",3/25/2016,,,,,,,,
19,The Dark Knight Rises,WB,"$160,887,295",7/20/2012,,,,,,,,
20,The Dark Knight,WB,"$158,411,483",7/18/2008,,,,,,,,
21,The Hunger Games: Catching Fire,LGF,"$158,074,286",11/22/2013,,,,,,,,
22,Rogue One: A Star Wars Story,BV,"$155,081,681",12/16/2016,,,,,,,,
23,The Hunger Games,LGF,"$152,535,747",3/23/2012,,,,,,,,
24,Spider-Man 3,Sony,"$151,116,516",5/4/2007,,,,,,,,
25,Jurassic World: Fallen Kingdom,Uni.,"$148,024,610",6/22/2018,,,,,,,,
26,Furious 7,Uni.,"$147,187,040",4/3/2015,,,,,,,,
27,Guardians of the Galaxy Vol. 2,BV,"$146,510,104",5/5/2017,,,,,,,,
28,The Twilight Saga: New Moon,Sum.,"$142,839,137",11/20/2009,,,,,,,,
29,The Twilight Saga: Breaking Dawn Part 2,LG/S,"$141,067,634",11/16/2012,,,,,,,,
30,The Twilight Saga: Breaking Dawn Part 1,Sum.,"$138,122,261",11/18/2011,,,,,,,,
31,Pirates of the Caribbean: Dead Man's Chest,BV,"$135,634,554",7/7/2006,,,,,,,,
32,Finding Dory,BV,"$135,060,273",6/17/2016,,,,,,,,
33,Suicide Squad,WB,"$133,682,248",8/5/2016,,,,,,,,
34,Deadpool,Fox,"$132,434,639",2/12/2016,,,,,,,,
35,Iron Man 2,Par.,"$128,122,480",5/7/2010,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...
672,The Little Rascals,Uni.,"$10,028,065",8/5/1994,,,,,,,,
673,Problem Child,Uni.,"$10,026,900",7/27/1990,,,,,,,,
674,The Reaping,WB,"$10,025,203",4/5/2007,,,,,,,,
675,The Last Mimzy,NL,"$10,024,819",3/23/2007,,,,,,,,
676,Valentine,WB,"$10,024,648",2/2/2001,,,,,,,,
677,Accepted,Uni.,"$10,023,835",8/18/2006,,,,,,,,
678,Boyz N the Hood,Col.,"$10,023,462",7/12/1991,,,,,,,,
679,The Untouchables,Par.,"$10,023,094",6/5/1987,,,,,,,,
680,The X-Files: I Want to Believe,Fox,"$10,021,753",7/25/2008,,,,,,,,
681,Fat Albert,Fox,"$10,021,510",12/25/2004,,,,,,,,
682,Conan the Barbarian (2011),LGF,"$10,021,215",8/19/2011,,,,,,,,
683,Seven Years in Tibet,Sony,"$10,020,378",10/10/1997,,,,,,,,
684,Dragon: The Bruce Lee Story,Uni.,"$10,019,970",5/7/1993,,,,,,,,
685,Mystery Men,Uni.,"$10,017,865",8/6/1999,,,,,,,,
686,Sea of Love,Uni.,"$10,017,840",9/15/1989,,,,,,,,
687,In Her Shoes,Fox,"$10,017,575",10/7/2005,,,,,,,,
688,Sleepwalkers,Col.,"$10,017,354",4/10/1992,,,,,,,,
689,Mr. Brooks,MGM,"$10,017,067",6/1/2007,,,,,,,,
690,Kidnap (2017),Aviron,"$10,016,323",8/4/2017,,,,,,,,
691,Rent,SonR,"$10,016,021",11/23/2005,,,,,,,,
692,Daylight,Uni.,"$10,015,875",12/6/1996,,,,,,,,
693,Final Destination,NL,"$10,015,822",3/17/2000,,,,,,,,
694,Rush (2013),Uni.,"$10,014,920",9/27/2013,,,,,,,,
695,The American President,Sony,"$10,014,558",11/17/1995,,,,,,,,
696,Fame (2009),MGM,"$10,011,682",9/25/2009,,,,,,,,
697,Someone Like You,Fox,"$10,010,600",3/30/2001,,,,,,,,
698,All About the Benjamins,NL,"$10,007,291",3/8/2002,,,,,,,,
699,The Black Dahlia,Uni.,"$10,005,895",9/15/2006,,,,,,,,
700,The Best of Me,Rela.,"$10,003,827",10/17/2014,,,,,,,,
701,Lawless,Wein.,"$10,001,982",8/29/2012,,,,,,,,

In [17]:
for i, r in weekend_box.iterrows():
    date = str(r['Date'])
    print(date)
    split = date.split('/')
    print(split)
    month = split[0]
    print(month)
    year = split[2]
    weekend_box.set_value(i, 'month', month)
    weekend_box.set_value(i, 'year', year)

4/27/2018
['4', '27', '2018']
4
12/18/2015
['12', '18', '2015']
12
12/15/2017
['12', '15', '2017']
12
6/12/2015
['6', '12', '2015']
6
5/4/2012
['5', '4', '2012']
5
2/16/2018
['2', '16', '2018']
2
5/1/2015
['5', '1', '2015']
5
6/15/2018
['6', '15', '2018']
6
5/6/2016
['5', '6', '2016']
5
3/17/2017
['3', '17', '2017']
3
5/3/2013
['5', '3', '2013']
5
7/15/2011
['7', '15', '2011']
7
3/25/2016
['3', '25', '2016']
3
7/20/2012
['7', '20', '2012']
7
7/18/2008
['7', '18', '2008']
7
11/22/2013
['11', '22', '2013']
11
12/16/2016
['12', '16', '2016']
12
3/23/2012
['3', '23', '2012']
3
5/4/2007
['5', '4', '2007']
5
6/22/2018
['6', '22', '2018']
6
4/3/2015
['4', '3', '2015']
4
5/5/2017
['5', '5', '2017']
5
11/20/2009
['11', '20', '2009']
11
11/16/2012
['11', '16', '2012']
11
11/18/2011
['11', '18', '2011']
11
7/7/2006
['7', '7', '2006']
7
6/17/2016
['6', '17', '2016']
6
8/5/2016
['8', '5', '2016']
8
2/12/2016
['2', '12', '2016']
2
5/7/2010
['5', '7', '2010']
5
5/18/2018
['5', '18', '2018']
5
11/19/2010
['11', '19', '2010']
11
9/8/2017
['9', '8', '2017']
9
11/3/2017
['11', '3', '2017']
11
11/21/2014
['11', '21', '2014']
11
5/18/2007
['5', '18', '2007']
5
7/7/2017
['7', '7', '2017']
7
6/14/2013
['6', '14', '2013']
6
3/5/2010
['3', '5', '2010']
3
7/10/2015
['7', '10', '2015']
7
5/3/2002
['5', '3', '2002']
5
5/25/2007
['5', '25', '2007']
5
6/18/2010
['6', '18', '2010']
6
6/24/2009
['6', '24', '2009']
6
5/19/2005
['5', '19', '2005']
5
5/19/2004
['5', '19', '2004']
5
7/8/2016
['7', '8', '2016']
7
4/15/2016
['4', '15', '2016']
4
6/2/2017
['6', '2', '2017']
6
5/26/2006
['5', '26', '2006']
5
11/18/2005
['11', '18', '2005']
11
11/20/2015
['11', '20', '2015']
11
5/22/2008
['5', '22', '2008']
5
6/27/2014
['6', '27', '2014']
6
4/14/2017
['4', '14', '2017']
4
5/2/2008
['5', '2', '2008']
5
6/29/2011
['6', '29', '2011']
6
5/24/2013
['5', '24', '2013']
5
4/4/2014
['4', '4', '2014']
4
8/1/2014
['8', '1', '2014']
8
11/17/2017
['11', '17', '2017']
11
6/4/2004
['6', '4', '2004']
6
5/16/2014
['5', '16', '2014']
5
5/15/2003
['5', '15', '2003']
5
5/2/2014
['5', '2', '2014']
5
5/23/2014
['5', '23', '2014']
5
6/19/2015
['6', '19', '2015']
6
11/16/2001
['11', '16', '2001']
11
5/20/2011
['5', '20', '2011']
5
1/16/2015
['1', '16', '2015']
1
3/3/2017
['3', '3', '2017']
3
11/9/2012
['11', '9', '2012']
11
11/15/2002
['11', '15', '2002']
11
6/30/2004
['6', '30', '2004']
6
4/29/2011
['4', '29', '2011']
4
5/26/2011
['5', '26', '2011']
5
11/8/2013
['11', '8', '2013']
11
5/2/2003
['5', '2', '2003']
5
2/13/2015
['2', '13', '2015']
2
11/4/2016
['11', '4', '2016']
11
5/1/2009
['5', '1', '2009']
5
12/14/2012
['12', '14', '2012']
12
5/25/2018
['5', '25', '2018']
5
2/25/2004
['2', '25', '2004']
2
7/3/2013
['7', '3', '2013']
7
6/21/2013
['6', '21', '2013']
6
5/16/2002
['5', '16', '2002']
5
3/8/2013
['3', '8', '2013']
3
7/15/2009
['7', '15', '2009']
7
12/14/2007
['12', '14', '2007']
12
7/11/2007
['7', '11', '2007']
7
5/19/2006
['5', '19', '2006']
5
12/18/2009
['12', '18', '2009']
12
5/8/2009
['5', '8', '2009']
5
3/4/2016
['3', '4', '2016']
3
11/18/2016
['11', '18', '2016']
11
7/27/2007
['7', '27', '2007']
7
12/13/2013
['12', '13', '2013']
12
7/26/2002
['7', '26', '2002']
7
12/17/2003
['12', '17', '2003']
12
7/11/2014
['7', '11', '2014']
7
6/30/2017
['6', '30', '2017']
6
5/23/1997
['5', '23', '1997']
5
4/3/2009
['4', '3', '2009']
4
3/9/2007
['3', '9', '2007']
3
5/21/2010
['5', '21', '2010']
5
7/3/2007
['7', '3', '2007']
7
11/5/2004
['11', '5', '2004']
11
11/6/2015
['11', '6', '2015']
11
5/30/2003
['5', '30', '2003']
5
3/2/2012
['3', '2', '2012']
3
5/16/2013
['5', '16', '2013']
5
11/21/2008
['11', '21', '2008']
11
5/30/2014
['5', '30', '2014']
5
8/3/2007
['8', '3', '2007']
8
5/15/2015
['5', '15', '2015']
5
2/7/2014
['2', '7', '2014']
2
5/28/2004
['5', '28', '2004']
5
7/27/2001
['7', '27', '2001']
7
5/4/2001
['5', '4', '2001']
5
5/29/2009
['5', '29', '2009']
5
3/31/2006
['3', '31', '2006']
3
5/23/2003
['5', '23', '2003']
5
3/13/2015
['3', '13', '2015']
3
11/14/2008
['11', '14', '2008']
11
8/3/2001
['8', '3', '2001']
8
11/27/2013
['11', '27', '2013']
11
6/21/2013
['6', '21', '2013']
6
6/22/2012
['6', '22', '2012']
6
6/24/2011
['6', '24', '2011']
6
5/27/2016
['5', '27', '2016']
5
5/6/2011
['5', '6', '2011']
5
8/8/2014
['8', '8', '2014']
8
12/9/2005
['12', '9', '2005']
12
11/13/2009
['11', '13', '2009']
11
7/22/2011
['7', '22', '2011']
7
6/29/2005
['6', '29', '2005']
6
6/30/2010
['6', '30', '2010']
6
5/19/1999
['5', '19', '1999']
5
11/7/2008
['11', '7', '2008']
11
6/27/2008
['6', '27', '2008']
6
5/26/2017
['5', '26', '2017']
5
7/16/2010
['7', '16', '2010']
7
7/2/2008
['7', '2', '2008']
7
11/2/2001
['11', '2', '2001']
11
12/25/2009
['12', '25', '2009']
12
6/20/2003
['6', '20', '2003']
6
12/18/2002
['12', '18', '2002']
12
7/3/2012
['7', '3', '2012']
7
4/2/2010
['4', '2', '2010']
4
3/10/2017
['3', '10', '2017']
3
6/8/2012
['6', '8', '2012']
6
6/6/2008
['6', '6', '2008']
6
8/14/2015
['8', '14', '2015']
8
6/9/2006
['6', '9', '2006']
6
8/2/2002
['8', '2', '2002']
8
3/27/2009
['3', '27', '2009']
3
7/22/2016
['7', '22', '2016']
7
7/29/2016
['7', '29', '2016']
7
5/25/2001
['5', '25', '2001']
5
6/15/2007
['6', '15', '2007']
6
2/9/2001
['2', '9', '2001']
2
5/24/2000
['5', '24', '2000']
5
11/24/1999
['11', '24', '1999']
11
7/17/2015
['7', '17', '2015']
7
6/13/2014
['6', '13', '2014']
6
5/30/2008
['5', '30', '2008']
5
11/23/2016
['11', '23', '2016']
11
7/9/2010
['7', '9', '2010']
7
7/14/2017
['7', '14', '2017']
7
2/12/2010
['2', '12', '2010']
2
6/1/2012
['6', '1', '2012']
6
11/7/2014
['11', '7', '2014']
11
7/15/2005
['7', '15', '2005']
7
7/8/2005
['7', '8', '2005']
7
10/4/2013
['10', '4', '2013']
10
6/11/2010
['6', '11', '2010']
6
7/31/2015
['7', '31', '2015']
7
6/13/2008
['6', '13', '2008']
6
2/6/2015
['2', '6', '2015']
2
3/6/2009
['3', '6', '2009']
3
6/3/2011
['6', '3', '2011']
6
11/17/2000
['11', '17', '2000']
11
5/16/2008
['5', '16', '2008']
5
6/11/1999
['6', '11', '1999']
6
8/5/2011
['8', '5', '2011']
8
12/17/2014
['12', '17', '2014']
12
8/7/2009
['8', '7', '2009']
8
3/21/2014
['3', '21', '2014']
3
5/25/2012
['5', '25', '2012']
5
5/29/2015
['5', '29', '2015']
5
7/14/2000
['7', '14', '2000']
7
6/29/2012
['6', '29', '2012']
6
10/2/2015
['10', '2', '2015']
10
5/22/2009
['5', '22', '2009']
5
6/14/2002
['6', '14', '2002']
6
6/16/2017
['6', '16', '2017']
6
6/17/2011
['6', '17', '2011']
6
7/26/2013
['7', '26', '2013']
7
2/10/2017
['2', '10', '2017']
2
6/16/1995
['6', '16', '1995']
6
10/21/2011
['10', '21', '2011']
10
6/28/2006
['6', '28', '2006']
6
7/23/2004
['7', '23', '2004']
7
3/20/2015
['3', '20', '2015']
3
7/16/2004
['7', '16', '2004']
7
7/3/2002
['7', '3', '2002']
7
3/27/2015
['3', '27', '2015']
3
5/7/2004
['5', '7', '2004']
5
11/8/2002
['11', '8', '2002']
11
7/2/1997
['7', '2', '1997']
7
6/8/2012
['6', '8', '2012']
6
6/27/2008
['6', '27', '2008']
6
11/22/2017
['11', '22', '2017']
11
7/18/2001
['7', '18', '2001']
7
7/30/2004
['7', '30', '2004']
7
7/21/2017
['7', '21', '2017']
7
6/6/2003
['6', '6', '2003']
6
10/15/2010
['10', '15', '2010']
10
6/10/2005
['6', '10', '2005']
6
7/3/1996
['7', '3', '1996']
7
4/6/2018
['4', '6', '2018']
4
3/31/2017
['3', '31', '2017']
3
12/14/2005
['12', '14', '2005']
12
5/10/2013
['5', '10', '2013']
5
nan
['nan']
nan

IndexError: list index out of range

In [20]:
weekend_box.head(12)

,Title,Studio,Opening,Date,Director,Budget,imdbID,month,year,Actor,Genre,Writer
6,Avengers: Infinity War,BV,"$257,698,183",4/27/2018,,,,4,2018,,,
7,Star Wars: The Force Awakens,BV,"$247,966,675",12/18/2015,,,,12,2015,,,
8,Star Wars: The Last Jedi,BV,"$220,009,584",12/15/2017,,,,12,2017,,,
9,Jurassic World,Uni.,"$208,806,270",6/12/2015,,,,6,2015,,,
10,Marvel's The Avengers,BV,"$207,438,708",5/4/2012,,,,5,2012,,,
11,Black Panther,BV,"$202,003,951",2/16/2018,,,,2,2018,,,
12,Avengers: Age of Ultron,BV,"$191,271,109",5/1/2015,,,,5,2015,,,
13,Incredibles 2,BV,"$182,687,905",6/15/2018,,,,6,2018,,,
14,Captain America: Civil War,BV,"$179,139,142",5/6/2016,,,,5,2016,,,
15,Beauty and the Beast (2017),BV,"$174,750,616",3/17/2017,,,,3,2017,,,
16,Iron Man 3,BV,"$174,144,585",5/3/2013,,,,5,2013,,,
17,Harry Potter and the Deathly Hallows Part 2,WB,"$169,189,427",7/15/2011,,,,7,2011,,,

In [21]:
year = weekend_box['year'] > str(2009)

In [22]:
weekend_box = weekend_box[year]

In [23]:
len(weekend_box)

797

In [24]:
omdb = 'http://www.omdbapi.com/?apikey=7b298284&t='

In [32]:
#add .head after weekend_box to limit API calls default number is 5
for index, row in weekend_box.iterrows():
    t = str(row['Title'])
    t = t.replace(":","")
    t = t.replace("'","")
    t = t.replace(' ', '+')
    search = omdb + t
    print (search)
    try:
        results = req.get(search).json()
        if results['Response'] == 'False':
            print("Couldn't find title: ", t)
        else:
            weekend_box.set_value(index, 'Director', results['Director'])
            weekend_box.set_value(index, 'imdbID', results['imdbID'])
            weekend_box.set_value(index, 'Actor', results['Actors'])
            weekend_box.set_value(index, 'Genre', results['Genre'])
            weekend_box.set_value(index, 'Writer', results['Writer'])
    except:
        print('in except')
        continue

http://www.omdbapi.com/?apikey=7b298284&t=Avengers+Infinity+War
http://www.omdbapi.com/?apikey=7b298284&t=Star+Wars+The+Force+Awakens
http://www.omdbapi.com/?apikey=7b298284&t=Star+Wars+The+Last+Jedi
http://www.omdbapi.com/?apikey=7b298284&t=Jurassic+World
http://www.omdbapi.com/?apikey=7b298284&t=Marvels+The+Avengers
Couldn't find title:  Marvels+The+Avengers
http://www.omdbapi.com/?apikey=7b298284&t=Black+Panther
http://www.omdbapi.com/?apikey=7b298284&t=Avengers+Age+of+Ultron
http://www.omdbapi.com/?apikey=7b298284&t=Incredibles+2
http://www.omdbapi.com/?apikey=7b298284&t=Captain+America+Civil+War
http://www.omdbapi.com/?apikey=7b298284&t=Beauty+and+the+Beast+(2017)
Couldn't find title:  Beauty+and+the+Beast+(2017)
http://www.omdbapi.com/?apikey=7b298284&t=Iron+Man+3
http://www.omdbapi.com/?apikey=7b298284&t=Harry+Potter+and+the+Deathly+Hallows+Part+2
http://www.omdbapi.com/?apikey=7b298284&t=Batman+v+Superman+Dawn+of+Justice
http://www.omdbapi.com/?apikey=7b298284&t=The+Dark+Knight+Rises
http://www.omdbapi.com/?apikey=7b298284&t=The+Hunger+Games+Catching+Fire
http://www.omdbapi.com/?apikey=7b298284&t=Rogue+One+A+Star+Wars+Story
http://www.omdbapi.com/?apikey=7b298284&t=The+Hunger+Games
http://www.omdbapi.com/?apikey=7b298284&t=Jurassic+World+Fallen+Kingdom
http://www.omdbapi.com/?apikey=7b298284&t=Furious+7
http://www.omdbapi.com/?apikey=7b298284&t=Guardians+of+the+Galaxy+Vol.+2
http://www.omdbapi.com/?apikey=7b298284&t=The+Twilight+Saga+Breaking+Dawn+Part+2
http://www.omdbapi.com/?apikey=7b298284&t=The+Twilight+Saga+Breaking+Dawn+Part+1
http://www.omdbapi.com/?apikey=7b298284&t=Finding+Dory
http://www.omdbapi.com/?apikey=7b298284&t=Suicide+Squad
http://www.omdbapi.com/?apikey=7b298284&t=Deadpool
http://www.omdbapi.com/?apikey=7b298284&t=Iron+Man+2
http://www.omdbapi.com/?apikey=7b298284&t=Deadpool+2
http://www.omdbapi.com/?apikey=7b298284&t=Harry+Potter+and+the+Deathly+Hallows+Part+1
http://www.omdbapi.com/?apikey=7b298284&t=It
http://www.omdbapi.com/?apikey=7b298284&t=Thor+Ragnarok
http://www.omdbapi.com/?apikey=7b298284&t=The+Hunger+Games+Mockingjay+-+Part+1
http://www.omdbapi.com/?apikey=7b298284&t=Spider-Man+Homecoming
http://www.omdbapi.com/?apikey=7b298284&t=Man+of+Steel
http://www.omdbapi.com/?apikey=7b298284&t=Alice+in+Wonderland+(2010)
Couldn't find title:  Alice+in+Wonderland+(2010)
http://www.omdbapi.com/?apikey=7b298284&t=Minions
http://www.omdbapi.com/?apikey=7b298284&t=Toy+Story+3
http://www.omdbapi.com/?apikey=7b298284&t=The+Secret+Life+of+Pets
http://www.omdbapi.com/?apikey=7b298284&t=The+Jungle+Book+(2016)
Couldn't find title:  The+Jungle+Book+(2016)
http://www.omdbapi.com/?apikey=7b298284&t=Wonder+Woman
http://www.omdbapi.com/?apikey=7b298284&t=The+Hunger+Games+Mockingjay+-+Part+2
http://www.omdbapi.com/?apikey=7b298284&t=Transformers+Age+of+Extinction
http://www.omdbapi.com/?apikey=7b298284&t=The+Fate+of+the+Furious
http://www.omdbapi.com/?apikey=7b298284&t=Transformers+Dark+of+the+Moon
http://www.omdbapi.com/?apikey=7b298284&t=Fast+&+Furious+6
http://www.omdbapi.com/?apikey=7b298284&t=Captain+America+The+Winter+Soldier
http://www.omdbapi.com/?apikey=7b298284&t=Guardians+of+the+Galaxy
http://www.omdbapi.com/?apikey=7b298284&t=Justice+League
http://www.omdbapi.com/?apikey=7b298284&t=Godzilla+(2014)
Couldn't find title:  Godzilla+(2014)
http://www.omdbapi.com/?apikey=7b298284&t=The+Amazing+Spider-Man+2
http://www.omdbapi.com/?apikey=7b298284&t=X-Men+Days+of+Future+Past
http://www.omdbapi.com/?apikey=7b298284&t=Inside+Out
http://www.omdbapi.com/?apikey=7b298284&t=Pirates+of+the+Caribbean+On+Stranger+Tides
http://www.omdbapi.com/?apikey=7b298284&t=American+Sniper
http://www.omdbapi.com/?apikey=7b298284&t=Logan
http://www.omdbapi.com/?apikey=7b298284&t=Skyfall
http://www.omdbapi.com/?apikey=7b298284&t=Fast+Five
http://www.omdbapi.com/?apikey=7b298284&t=The+Hangover+Part+II
http://www.omdbapi.com/?apikey=7b298284&t=Thor+The+Dark+World
http://www.omdbapi.com/?apikey=7b298284&t=Fifty+Shades+of+Grey
http://www.omdbapi.com/?apikey=7b298284&t=Doctor+Strange
http://www.omdbapi.com/?apikey=7b298284&t=The+Hobbit+An+Unexpected+Journey
http://www.omdbapi.com/?apikey=7b298284&t=Solo+A+Star+Wars+Story
http://www.omdbapi.com/?apikey=7b298284&t=Despicable+Me+2
http://www.omdbapi.com/?apikey=7b298284&t=Monsters+University
http://www.omdbapi.com/?apikey=7b298284&t=Oz+The+Great+and+Powerful
http://www.omdbapi.com/?apikey=7b298284&t=Zootopia
http://www.omdbapi.com/?apikey=7b298284&t=Fantastic+Beasts+and+Where+To+Find+Them
http://www.omdbapi.com/?apikey=7b298284&t=The+Hobbit+The+Desolation+of+Smaug
http://www.omdbapi.com/?apikey=7b298284&t=Dawn+of+the+Planet+of+the+Apes
http://www.omdbapi.com/?apikey=7b298284&t=Despicable+Me+3
http://www.omdbapi.com/?apikey=7b298284&t=Shrek+Forever+After
http://www.omdbapi.com/?apikey=7b298284&t=Spectre
http://www.omdbapi.com/?apikey=7b298284&t=Dr.+Seuss+The+Lorax
Couldn't find title:  Dr.+Seuss+The+Lorax
http://www.omdbapi.com/?apikey=7b298284&t=Star+Trek+Into+Darkness
http://www.omdbapi.com/?apikey=7b298284&t=Maleficent
http://www.omdbapi.com/?apikey=7b298284&t=Pitch+Perfect+2
http://www.omdbapi.com/?apikey=7b298284&t=The+LEGO+Movie
http://www.omdbapi.com/?apikey=7b298284&t=Cinderella+(2015)
Couldn't find title:  Cinderella+(2015)
http://www.omdbapi.com/?apikey=7b298284&t=Frozen
http://www.omdbapi.com/?apikey=7b298284&t=World+War+Z
http://www.omdbapi.com/?apikey=7b298284&t=Brave
http://www.omdbapi.com/?apikey=7b298284&t=Cars+2
http://www.omdbapi.com/?apikey=7b298284&t=X-Men+Apocalypse
http://www.omdbapi.com/?apikey=7b298284&t=Thor
http://www.omdbapi.com/?apikey=7b298284&t=Teenage+Mutant+Ninja+Turtles+(2014)
Couldn't find title:  Teenage+Mutant+Ninja+Turtles+(2014)
http://www.omdbapi.com/?apikey=7b298284&t=Captain+America+The+First+Avenger
http://www.omdbapi.com/?apikey=7b298284&t=The+Twilight+Saga+Eclipse
http://www.omdbapi.com/?apikey=7b298284&t=Pirates+of+the+Caribbean+Dead+Men+Tell+No+Tales
http://www.omdbapi.com/?apikey=7b298284&t=Inception
http://www.omdbapi.com/?apikey=7b298284&t=The+Amazing+Spider-Man
http://www.omdbapi.com/?apikey=7b298284&t=Clash+of+the+Titans+(2010)
Couldn't find title:  Clash+of+the+Titans+(2010)
http://www.omdbapi.com/?apikey=7b298284&t=Kong+Skull+Island
http://www.omdbapi.com/?apikey=7b298284&t=Madagascar+3+Europes+Most+Wanted
Couldn't find title:  Madagascar+3+Europes+Most+Wanted
http://www.omdbapi.com/?apikey=7b298284&t=Straight+Outta+Compton
http://www.omdbapi.com/?apikey=7b298284&t=Star+Trek+Beyond
http://www.omdbapi.com/?apikey=7b298284&t=Jason+Bourne
http://www.omdbapi.com/?apikey=7b298284&t=Ant-Man
http://www.omdbapi.com/?apikey=7b298284&t=22+Jump+Street
http://www.omdbapi.com/?apikey=7b298284&t=Moana
http://www.omdbapi.com/?apikey=7b298284&t=Despicable+Me
http://www.omdbapi.com/?apikey=7b298284&t=War+for+the+Planet+of+the+Apes
http://www.omdbapi.com/?apikey=7b298284&t=Valentines+Day
http://www.omdbapi.com/?apikey=7b298284&t=Snow+White+and+the+Huntsman
http://www.omdbapi.com/?apikey=7b298284&t=Big+Hero+6
http://www.omdbapi.com/?apikey=7b298284&t=Gravity
http://www.omdbapi.com/?apikey=7b298284&t=The+Karate+Kid
http://www.omdbapi.com/?apikey=7b298284&t=Mission+Impossible+-+Rogue+Nation
http://www.omdbapi.com/?apikey=7b298284&t=The+SpongeBob+Movie+Sponge+Out+of+Water
http://www.omdbapi.com/?apikey=7b298284&t=X-Men+First+Class
http://www.omdbapi.com/?apikey=7b298284&t=Rise+of+the+Planet+of+the+Apes
http://www.omdbapi.com/?apikey=7b298284&t=The+Hobbit+The+Battle+of+the+Five+Armies
http://www.omdbapi.com/?apikey=7b298284&t=Divergent
http://www.omdbapi.com/?apikey=7b298284&t=MIB+3
http://www.omdbapi.com/?apikey=7b298284&t=San+Andreas
http://www.omdbapi.com/?apikey=7b298284&t=Ted
http://www.omdbapi.com/?apikey=7b298284&t=The+Martian
http://www.omdbapi.com/?apikey=7b298284&t=Cars+3
http://www.omdbapi.com/?apikey=7b298284&t=Green+Lantern
http://www.omdbapi.com/?apikey=7b298284&t=The+Wolverine
http://www.omdbapi.com/?apikey=7b298284&t=The+LEGO+Batman+Movie
http://www.omdbapi.com/?apikey=7b298284&t=Paranormal+Activity+3
http://www.omdbapi.com/?apikey=7b298284&t=The+Divergent+Series+Insurgent
Couldn't find title:  The+Divergent+Series+Insurgent
http://www.omdbapi.com/?apikey=7b298284&t=Home+(2015)
Couldn't find title:  Home+(2015)
http://www.omdbapi.com/?apikey=7b298284&t=Prometheus
http://www.omdbapi.com/?apikey=7b298284&t=Coco

http://www.omdbapi.com/?apikey=7b298284&t=Dunkirk
http://www.omdbapi.com/?apikey=7b298284&t=Jackass+3-D
Couldn't find title:  Jackass+3-D
http://www.omdbapi.com/?apikey=7b298284&t=A+Quiet+Place
http://www.omdbapi.com/?apikey=7b298284&t=The+Boss+Baby
http://www.omdbapi.com/?apikey=7b298284&t=The+Great+Gatsby+(2013)
Couldn't find title:  The+Great+Gatsby+(2013)
http://www.omdbapi.com/?apikey=7b298284&t=Taken+2
http://www.omdbapi.com/?apikey=7b298284&t=How+to+Train+Your+Dragon+2
http://www.omdbapi.com/?apikey=7b298284&t=Rush+Hour+3
http://www.omdbapi.com/?apikey=7b298284&t=Wreck-It+Ralph
http://www.omdbapi.com/?apikey=7b298284&t=Neighbors
http://www.omdbapi.com/?apikey=7b298284&t=Alvin+and+the+Chipmunks+The+Squeakquel
http://www.omdbapi.com/?apikey=7b298284&t=Tangled
http://www.omdbapi.com/?apikey=7b298284&t=Batman+Begins
http://www.omdbapi.com/?apikey=7b298284&t=The+Matrix+Revolutions
http://www.omdbapi.com/?apikey=7b298284&t=Hotel+Transylvania+2
http://www.omdbapi.com/?apikey=7b298284&t=Scary+Movie+3
http://www.omdbapi.com/?apikey=7b298284&t=The+Fault+in+our+Stars
http://www.omdbapi.com/?apikey=7b298284&t=Mission+Impossible+III
http://www.omdbapi.com/?apikey=7b298284&t=Lara+Croft+Tomb+Raider
http://www.omdbapi.com/?apikey=7b298284&t=The+Longest+Yard
http://www.omdbapi.com/?apikey=7b298284&t=Shark+Tale
http://www.omdbapi.com/?apikey=7b298284&t=Interstellar
http://www.omdbapi.com/?apikey=7b298284&t=The+Lord+of+the+Rings+The+Fellowship+of+the+Ring
http://www.omdbapi.com/?apikey=7b298284&t=Die+Another+Day
http://www.omdbapi.com/?apikey=7b298284&t=Talladega+Nights+The+Ballad+of+Ricky+Bobby
http://www.omdbapi.com/?apikey=7b298284&t=Jurassic+Park
http://www.omdbapi.com/?apikey=7b298284&t=Troy
http://www.omdbapi.com/?apikey=7b298284&t=Ice+Age+Continental+Drift
http://www.omdbapi.com/?apikey=7b298284&t=Fifty+Shades+Darker
http://www.omdbapi.com/?apikey=7b298284&t=Trolls
http://www.omdbapi.com/?apikey=7b298284&t=Bad+Boys+II
http://www.omdbapi.com/?apikey=7b298284&t=Ice+Age
http://www.omdbapi.com/?apikey=7b298284&t=Angels+&+Demons
http://www.omdbapi.com/?apikey=7b298284&t=Meet+the+Fockers
http://www.omdbapi.com/?apikey=7b298284&t=Ghostbusters+(2016)
http://www.omdbapi.com/?apikey=7b298284&t=Megamind
http://www.omdbapi.com/?apikey=7b298284&t=Mission+Impossible
http://www.omdbapi.com/?apikey=7b298284&t=Mad+Max+Fury+Road
http://www.omdbapi.com/?apikey=7b298284&t=Ghost+Rider
http://www.omdbapi.com/?apikey=7b298284&t=American+Pie+2
in except
http://www.omdbapi.com/?apikey=7b298284&t=The+Hangover
http://www.omdbapi.com/?apikey=7b298284&t=Alvin+and+the+Chipmunks
http://www.omdbapi.com/?apikey=7b298284&t=The+Peanuts+Movie
http://www.omdbapi.com/?apikey=7b298284&t=Godzilla
http://www.omdbapi.com/?apikey=7b298284&t=Lucy
http://www.omdbapi.com/?apikey=7b298284&t=Noah
http://www.omdbapi.com/?apikey=7b298284&t=The+Croods
http://www.omdbapi.com/?apikey=7b298284&t=The+Mummy
http://www.omdbapi.com/?apikey=7b298284&t=Hitch
http://www.omdbapi.com/?apikey=7b298284&t=Batman+and+Robin
http://www.omdbapi.com/?apikey=7b298284&t=Terminator+Salvation
http://www.omdbapi.com/?apikey=7b298284&t=Hotel+Transylvania
http://www.omdbapi.com/?apikey=7b298284&t=Shrek
http://www.omdbapi.com/?apikey=7b298284&t=Anger+Management
http://www.omdbapi.com/?apikey=7b298284&t=High+School+Musical+3+Senior+Year
http://www.omdbapi.com/?apikey=7b298284&t=The+Conjuring
http://www.omdbapi.com/?apikey=7b298284&t=Ice+Age+Dawn+of+the+Dinosaurs
http://www.omdbapi.com/?apikey=7b298284&t=The+Hangover+Part+III
http://www.omdbapi.com/?apikey=7b298284&t=Oceans+8
http://www.omdbapi.com/?apikey=7b298284&t=Big+Daddy
http://www.omdbapi.com/?apikey=7b298284&t=Grown+Ups+2
http://www.omdbapi.com/?apikey=7b298284&t=The+Perfect+Storm
http://www.omdbapi.com/?apikey=7b298284&t=Kung+Fu+Panda+3
http://www.omdbapi.com/?apikey=7b298284&t=Deep+Impact
http://www.omdbapi.com/?apikey=7b298284&t=Shutter+Island
http://www.omdbapi.com/?apikey=7b298284&t=Independence+Day+Resurgence
http://www.omdbapi.com/?apikey=7b298284&t=Tyler+Perrys+Madea+Goes+to+Jail
Couldn't find title:  Tyler+Perrys+Madea+Goes+to+Jail
http://www.omdbapi.com/?apikey=7b298284&t=Casino+Royale
http://www.omdbapi.com/?apikey=7b298284&t=Paranormal+Activity+2
http://www.omdbapi.com/?apikey=7b298284&t=Grown+Ups
http://www.omdbapi.com/?apikey=7b298284&t=Power+Rangers+(2017)
Couldn't find title:  Power+Rangers+(2017)
http://www.omdbapi.com/?apikey=7b298284&t=Insidious+Chapter+2
http://www.omdbapi.com/?apikey=7b298284&t=Safe+House
http://www.omdbapi.com/?apikey=7b298284&t=Cloverfield
http://www.omdbapi.com/?apikey=7b298284&t=Chicken+Little
http://www.omdbapi.com/?apikey=7b298284&t=50+First+Dates
http://www.omdbapi.com/?apikey=7b298284&t=The+Revenant
http://www.omdbapi.com/?apikey=7b298284&t=Wild+Hogs
http://www.omdbapi.com/?apikey=7b298284&t=Sherlock+Holmes+A+Game+of+Shadows
http://www.omdbapi.com/?apikey=7b298284&t=The+Waterboy
http://www.omdbapi.com/?apikey=7b298284&t=Rio+2
http://www.omdbapi.com/?apikey=7b298284&t=Rio
http://www.omdbapi.com/?apikey=7b298284&t=Taken+3
http://www.omdbapi.com/?apikey=7b298284&t=The+Break-Up
http://www.omdbapi.com/?apikey=7b298284&t=The+Good+Dinosaur
http://www.omdbapi.com/?apikey=7b298284&t=Oceans+Twelve
Couldn't find title:  Oceans+Twelve
http://www.omdbapi.com/?apikey=7b298284&t=The+Grudge
http://www.omdbapi.com/?apikey=7b298284&t=Magic+Mike
http://www.omdbapi.com/?apikey=7b298284&t=The+Heat
http://www.omdbapi.com/?apikey=7b298284&t=Dinosaur
http://www.omdbapi.com/?apikey=7b298284&t=Daddys+Home
Couldn't find title:  Daddys+Home
http://www.omdbapi.com/?apikey=7b298284&t=Get+Smart
http://www.omdbapi.com/?apikey=7b298284&t=You+Dont+Mess+with+the+Zohan
Couldn't find title:  You+Dont+Mess+with+the+Zohan
http://www.omdbapi.com/?apikey=7b298284&t=The+Legend+of+Tarzan
http://www.omdbapi.com/?apikey=7b298284&t=Over+the+Hedge
http://www.omdbapi.com/?apikey=7b298284&t=Alien+Vs.+Predator
Couldn't find title:  Alien+Vs.+Predator
http://www.omdbapi.com/?apikey=7b298284&t=The+Angry+Birds+Movie
http://www.omdbapi.com/?apikey=7b298284&t=Oceans+Eleven
Couldn't find title:  Oceans+Eleven
http://www.omdbapi.com/?apikey=7b298284&t=Rango
http://www.omdbapi.com/?apikey=7b298284&t=Inglourious+Basterds
http://www.omdbapi.com/?apikey=7b298284&t=Bee+Movie
http://www.omdbapi.com/?apikey=7b298284&t=Lone+Survivor
http://www.omdbapi.com/?apikey=7b298284&t=Ace+Ventura+When+Nature+Calls
http://www.omdbapi.com/?apikey=7b298284&t=Charlies+Angels+Full+Throttle
Couldn't find title:  Charlies+Angels+Full+Throttle
http://www.omdbapi.com/?apikey=7b298284&t=Hop
http://www.omdbapi.com/?apikey=7b298284&t=Gone+Girl
http://www.omdbapi.com/?apikey=7b298284&t=Pacific+Rim
http://www.omdbapi.com/?apikey=7b298284&t=Mr.+Deeds
http://www.omdbapi.com/?apikey=7b298284&t=Annabelle
http://www.omdbapi.com/?apikey=7b298284&t=Air+Force+One
http://www.omdbapi.com/?apikey=7b298284&t=Red+Dragon
http://www.omdbapi.com/?apikey=7b298284&t=Marley+and+Me
Couldn't find title:  Marley+and+Me
http://www.omdbapi.com/?apikey=7b298284&t=21+Jump+Street
http://www.omdbapi.com/?apikey=7b298284&t=Kingsman+The+Secret+Service
http://www.omdbapi.com/?apikey=7b298284&t=Oceans+Thirteen
Couldn't find title:  Oceans+Thirteen
http://www.omdbapi.com/?apikey=7b298284&t=Armageddon
http://www.omdbapi.com/?apikey=7b298284&t=The+Scorpion+King
http://www.omdbapi.com/?apikey=7b298284&t=Robots
http://www.omdbapi.com/?apikey=7b298284&t=Salt
http://www.omdbapi.com/?apikey=7b298284&t=Star+Wars+(Special+Edition)
Couldn't find title:  Star+Wars+(Special+Edition)
http://www.omdbapi.com/?apikey=7b298284&t=10,000+B.C.
http://www.omdbapi.com/?apikey=7b298284&t=Rampage+(2018)
Couldn't find title:  Rampage+(2018)
http://www.omdbapi.com/?apikey=7b298284&t=Sweet+Home+Alabama
http://www.omdbapi.com/?apikey=7b298284&t=Battle+Los+Angeles
http://www.omdbapi.com/?apikey=7b298284&t=The+Other+Guys
http://www.omdbapi.com/?apikey=7b298284&t=Central+Intelligence
http://www.omdbapi.com/?apikey=7b298284&t=Super+8
http://www.omdbapi.com/?apikey=7b298284&t=Teenage+Mutant+Ninja+Turtles+Out+of+the+Shadows
http://www.omdbapi.com/?apikey=7b298284&t=Lilo+&+Stitch
http://www.omdbapi.com/?apikey=7b298284&t=Sing
http://www.omdbapi.com/?apikey=7b298284&t=The+Ring+Two
http://www.omdbapi.com/?apikey=7b298284&t=Runaway+Bride
http://www.omdbapi.com/?apikey=7b298284&t=Sully

http://www.omdbapi.com/?apikey=7b298284&t=The+Expendables
http://www.omdbapi.com/?apikey=7b298284&t=Gladiator
http://www.omdbapi.com/?apikey=7b298284&t=The+Magnificent+Seven+(2016)
Couldn't find title:  The+Magnificent+Seven+(2016)
http://www.omdbapi.com/?apikey=7b298284&t=Identity+Thief
http://www.omdbapi.com/?apikey=7b298284&t=Enchanted
http://www.omdbapi.com/?apikey=7b298284&t=Couples+Retreat
http://www.omdbapi.com/?apikey=7b298284&t=I+Now+Pronounce+You+Chuck+and+Larry
Couldn't find title:  I+Now+Pronounce+You+Chuck+and+Larry
http://www.omdbapi.com/?apikey=7b298284&t=The+Purge
http://www.omdbapi.com/?apikey=7b298284&t=Lethal+Weapon+4
http://www.omdbapi.com/?apikey=7b298284&t=Wedding+Crashers
http://www.omdbapi.com/?apikey=7b298284&t=Think+Like+a+Man
http://www.omdbapi.com/?apikey=7b298284&t=The+Proposal
http://www.omdbapi.com/?apikey=7b298284&t=The+Green+Hornet
http://www.omdbapi.com/?apikey=7b298284&t=Wrath+of+the+Titans
http://www.omdbapi.com/?apikey=7b298284&t=Spy+Kids+3D+Game+Over
Couldn't find title:  Spy+Kids+3D+Game+Over
http://www.omdbapi.com/?apikey=7b298284&t=Get+Out
http://www.omdbapi.com/?apikey=7b298284&t=American+Wedding
http://www.omdbapi.com/?apikey=7b298284&t=Lethal+Weapon+3
http://www.omdbapi.com/?apikey=7b298284&t=A+Wrinkle+in+Time
http://www.omdbapi.com/?apikey=7b298284&t=The+Book+of+Eli
http://www.omdbapi.com/?apikey=7b298284&t=Due+Date
http://www.omdbapi.com/?apikey=7b298284&t=Blade+II
http://www.omdbapi.com/?apikey=7b298284&t=The+Maze+Runner
http://www.omdbapi.com/?apikey=7b298284&t=Hannah+Montana+The+Movie
http://www.omdbapi.com/?apikey=7b298284&t=Mr.+Peabody+&+Sherman
http://www.omdbapi.com/?apikey=7b298284&t=Immortals
http://www.omdbapi.com/?apikey=7b298284&t=Jackass+Presents+Bad+Grandpa
Couldn't find title:  Jackass+Presents+Bad+Grandpa
http://www.omdbapi.com/?apikey=7b298284&t=Terminator+2+Judgment+Day
http://www.omdbapi.com/?apikey=7b298284&t=Saw+II
http://www.omdbapi.com/?apikey=7b298284&t=The+Truman+Show
http://www.omdbapi.com/?apikey=7b298284&t=The+Purge+Election+Year
http://www.omdbapi.com/?apikey=7b298284&t=The+Sum+of+All+Fears
http://www.omdbapi.com/?apikey=7b298284&t=Home+Alone+2+Lost+in+New+York
http://www.omdbapi.com/?apikey=7b298284&t=Hannah+Montana/Miley+Cyrus+Best+of+Both+Worlds+Concert+Tour
Couldn't find title:  Hannah+Montana/Miley+Cyrus+Best+of+Both+Worlds+Concert+Tour
http://www.omdbapi.com/?apikey=7b298284&t=Elf
http://www.omdbapi.com/?apikey=7b298284&t=Four+Christmases
http://www.omdbapi.com/?apikey=7b298284&t=Step+Brothers
http://www.omdbapi.com/?apikey=7b298284&t=Little+Fockers
http://www.omdbapi.com/?apikey=7b298284&t=Saving+Private+Ryan
http://www.omdbapi.com/?apikey=7b298284&t=The+Pacifier
http://www.omdbapi.com/?apikey=7b298284&t=The+Happening
http://www.omdbapi.com/?apikey=7b298284&t=Just+Go+With+It
http://www.omdbapi.com/?apikey=7b298284&t=The+Day+the+Earth+Stood+Still+(2008)
Couldn't find title:  The+Day+the+Earth+Stood+Still+(2008)
http://www.omdbapi.com/?apikey=7b298284&t=Dear+John
http://www.omdbapi.com/?apikey=7b298284&t=John+Wick+Chapter+Two
Couldn't find title:  John+Wick+Chapter+Two
http://www.omdbapi.com/?apikey=7b298284&t=Night+at+the+Museum
http://www.omdbapi.com/?apikey=7b298284&t=Maze+Runner+The+Scorch+Trials
http://www.omdbapi.com/?apikey=7b298284&t=Cloudy+with+a+Chance+of+Meatballs
http://www.omdbapi.com/?apikey=7b298284&t=Americas+Sweethearts
Couldn't find title:  Americas+Sweethearts
http://www.omdbapi.com/?apikey=7b298284&t=The+Lion+King+(in+3D)
Couldn't find title:  The+Lion+King+(in+3D)
http://www.omdbapi.com/?apikey=7b298284&t=Django+Unchained
http://www.omdbapi.com/?apikey=7b298284&t=DodgeBall+A+True+Underdog+Story
http://www.omdbapi.com/?apikey=7b298284&t=Lemony+Snickets+A+Series+of+Unfortunate+Events
Couldn't find title:  Lemony+Snickets+A+Series+of+Unfortunate+Events
http://www.omdbapi.com/?apikey=7b298284&t=Panic+Room
http://www.omdbapi.com/?apikey=7b298284&t=The+Exorcism+of+Emily+Rose
http://www.omdbapi.com/?apikey=7b298284&t=Saw+V
http://www.omdbapi.com/?apikey=7b298284&t=A+Christmas+Carol+(2009)
Couldn't find title:  A+Christmas+Carol+(2009)
http://www.omdbapi.com/?apikey=7b298284&t=Tyler+Perrys+Madeas+Family+Reunion
Couldn't find title:  Tyler+Perrys+Madeas+Family+Reunion
http://www.omdbapi.com/?apikey=7b298284&t=The+Purge+Anarchy
http://www.omdbapi.com/?apikey=7b298284&t=Elysium
http://www.omdbapi.com/?apikey=7b298284&t=Hercules+(2014)
Couldn't find title:  Hercules+(2014)
http://www.omdbapi.com/?apikey=7b298284&t=Constantine
http://www.omdbapi.com/?apikey=7b298284&t=What+Lies+Beneath
http://www.omdbapi.com/?apikey=7b298284&t=The+Flintstones
http://www.omdbapi.com/?apikey=7b298284&t=Dark+Shadows
http://www.omdbapi.com/?apikey=7b298284&t=Daddys+Home+2
Couldn't find title:  Daddys+Home+2
http://www.omdbapi.com/?apikey=7b298284&t=Creed
http://www.omdbapi.com/?apikey=7b298284&t=Insidious+The+Last+Key
http://www.omdbapi.com/?apikey=7b298284&t=Mission+Impossible+-+Ghost+Protocol
http://www.omdbapi.com/?apikey=7b298284&t=Pocahontas
http://www.omdbapi.com/?apikey=7b298284&t=Justin+Bieber+Never+Say+Never
http://www.omdbapi.com/?apikey=7b298284&t=Gran+Torino
http://www.omdbapi.com/?apikey=7b298284&t=Scooby-Doo+2+Monsters+Unleashed
http://www.omdbapi.com/?apikey=7b298284&t=Indiana+Jones+and+the+Last+Crusade
http://www.omdbapi.com/?apikey=7b298284&t=A.I.+Artificial+Intelligence
http://www.omdbapi.com/?apikey=7b298284&t=Beverly+Hills+Chihuahua
http://www.omdbapi.com/?apikey=7b298284&t=Tyler+Perrys+Why+Did+I+Get+Married+Too?
Couldn't find title:  Tyler+Perrys+Why+Did+I+Get+Married+Too?
http://www.omdbapi.com/?apikey=7b298284&t=Think+Like+a+Man+Too
http://www.omdbapi.com/?apikey=7b298284&t=The+Lone+Ranger
http://www.omdbapi.com/?apikey=7b298284&t=The+Blair+Witch+Project
http://www.omdbapi.com/?apikey=7b298284&t=Toy+Story
http://www.omdbapi.com/?apikey=7b298284&t=Sin+City
http://www.omdbapi.com/?apikey=7b298284&t=Spy
http://www.omdbapi.com/?apikey=7b298284&t=The+Divergent+Series+Allegiant
Couldn't find title:  The+Divergent+Series+Allegiant
http://www.omdbapi.com/?apikey=7b298284&t=Doctor+Dolittle
http://www.omdbapi.com/?apikey=7b298284&t=The+Santa+Clause+2
http://www.omdbapi.com/?apikey=7b298284&t=Paranormal+Activity+4
http://www.omdbapi.com/?apikey=7b298284&t=Jackass+Number+Two
http://www.omdbapi.com/?apikey=7b298284&t=Inside+Man
http://www.omdbapi.com/?apikey=7b298284&t=Non-Stop
http://www.omdbapi.com/?apikey=7b298284&t=Miss+Peregrines+Home+for+Peculiar+Children
Couldn't find title:  Miss+Peregrines+Home+for+Peculiar+Children
http://www.omdbapi.com/?apikey=7b298284&t=Edge+of+Tomorrow
http://www.omdbapi.com/?apikey=7b298284&t=Murder+on+the+Orient+Express+(2017)
Couldn't find title:  Murder+on+the+Orient+Express+(2017)
http://www.omdbapi.com/?apikey=7b298284&t=Obsessed
http://www.omdbapi.com/?apikey=7b298284&t=Anchorman+The+Legend+of+Ron+Burgundy
http://www.omdbapi.com/?apikey=7b298284&t=Mama
http://www.omdbapi.com/?apikey=7b298284&t=Nacho+Libre
http://www.omdbapi.com/?apikey=7b298284&t=Pacific+Rim+Uprising
http://www.omdbapi.com/?apikey=7b298284&t=The+Texas+Chainsaw+Massacre
http://www.omdbapi.com/?apikey=7b298284&t=Back+to+the+Future+Part+II
http://www.omdbapi.com/?apikey=7b298284&t=Hes+Just+Not+That+Into+You
Couldn't find title:  Hes+Just+Not+That+Into+You
http://www.omdbapi.com/?apikey=7b298284&t=Mamma+Mia!
http://www.omdbapi.com/?apikey=7b298284&t=Big+Mommas+House+2
Couldn't find title:  Big+Mommas+House+2
http://www.omdbapi.com/?apikey=7b298284&t=Jarhead
http://www.omdbapi.com/?apikey=7b298284&t=Along+Came+Polly
http://www.omdbapi.com/?apikey=7b298284&t=Daddy+Day+Care
http://www.omdbapi.com/?apikey=7b298284&t=Cheaper+by+the+Dozen
http://www.omdbapi.com/?apikey=7b298284&t=Wonder
http://www.omdbapi.com/?apikey=7b298284&t=The+Devil+Wears+Prada
http://www.omdbapi.com/?apikey=7b298284&t=After+Earth
http://www.omdbapi.com/?apikey=7b298284&t=Beowulf
in except
http://www.omdbapi.com/?apikey=7b298284&t=42
http://www.omdbapi.com/?apikey=7b298284&t=Hairspray+(2007)
Couldn't find title:  Hairspray+(2007)
http://www.omdbapi.com/?apikey=7b298284&t=Jumper
http://www.omdbapi.com/?apikey=7b298284&t=Journey+2+The+Mysterious+Island
http://www.omdbapi.com/?apikey=7b298284&t=The+Rugrats+Movie
http://www.omdbapi.com/?apikey=7b298284&t=Les+Miserables+(2012)

in except
http://www.omdbapi.com/?apikey=7b298284&t=Jack+the+Giant+Slayer
http://www.omdbapi.com/?apikey=7b298284&t=2+Guns
http://www.omdbapi.com/?apikey=7b298284&t=Terminator+Genisys
http://www.omdbapi.com/?apikey=7b298284&t=The+Departed
http://www.omdbapi.com/?apikey=7b298284&t=Alice+Through+the+Looking+Glass
http://www.omdbapi.com/?apikey=7b298284&t=The+Curious+Case+of+Benjamin+Button
http://www.omdbapi.com/?apikey=7b298284&t=The+Pursuit+of+Happyness
http://www.omdbapi.com/?apikey=7b298284&t=Borat+Cultural+Learnings+of+America+for+Make+Benefit+Glorious+Nation+of+Kazakhstan
http://www.omdbapi.com/?apikey=7b298284&t=Were+the+Millers
Couldn't find title:  Were+the+Millers
http://www.omdbapi.com/?apikey=7b298284&t=Halloween+(2007)
Couldn't find title:  Halloween+(2007)
http://www.omdbapi.com/?apikey=7b298284&t=Beverly+Hills+Cop+II
http://www.omdbapi.com/?apikey=7b298284&t=GoldenEye
http://www.omdbapi.com/?apikey=7b298284&t=The+Perfect+Guy
http://www.omdbapi.com/?apikey=7b298284&t=Tropic+Thunder
http://www.omdbapi.com/?apikey=7b298284&t=The+Golden+Compass
http://www.omdbapi.com/?apikey=7b298284&t=Miami+Vice
http://www.omdbapi.com/?apikey=7b298284&t=Fantastic+Four
http://www.omdbapi.com/?apikey=7b298284&t=The+A-Team
http://www.omdbapi.com/?apikey=7b298284&t=Battleship
http://www.omdbapi.com/?apikey=7b298284&t=The+Visit
http://www.omdbapi.com/?apikey=7b298284&t=The+Nutty+Professor+(1996)
Couldn't find title:  The+Nutty+Professor+(1996)
http://www.omdbapi.com/?apikey=7b298284&t=The+Firm
http://www.omdbapi.com/?apikey=7b298284&t=Teenage+Mutant+Ninja+Turtles
http://www.omdbapi.com/?apikey=7b298284&t=Tyler+Perrys+Madeas+Witness+Protection
Couldn't find title:  Tyler+Perrys+Madeas+Witness+Protection
http://www.omdbapi.com/?apikey=7b298284&t=Gnomeo+and+Juliet
Couldn't find title:  Gnomeo+and+Juliet
http://www.omdbapi.com/?apikey=7b298284&t=Apollo+13
http://www.omdbapi.com/?apikey=7b298284&t=Underworld+Awakening
http://www.omdbapi.com/?apikey=7b298284&t=Patch+Adams
http://www.omdbapi.com/?apikey=7b298284&t=Master+and+Commander+The+Far+Side+of+the+World
http://www.omdbapi.com/?apikey=7b298284&t=Kill+Bill+Vol.+2
http://www.omdbapi.com/?apikey=7b298284&t=Jack+and+Jill
http://www.omdbapi.com/?apikey=7b298284&t=nan
http://www.omdbapi.com/?apikey=7b298284&t=Flight
http://www.omdbapi.com/?apikey=7b298284&t=White+House+Down
http://www.omdbapi.com/?apikey=7b298284&t=A+Good+Day+to+Die+Hard
http://www.omdbapi.com/?apikey=7b298284&t=True+Grit
http://www.omdbapi.com/?apikey=7b298284&t=The+Other+Woman+(2014)
Couldn't find title:  The+Other+Woman+(2014)
http://www.omdbapi.com/?apikey=7b298284&t=Predators
http://www.omdbapi.com/?apikey=7b298284&t=Zombieland
http://www.omdbapi.com/?apikey=7b298284&t=10+Cloverfield+Lane
http://www.omdbapi.com/?apikey=7b298284&t=Taken
http://www.omdbapi.com/?apikey=7b298284&t=The+Accountant
http://www.omdbapi.com/?apikey=7b298284&t=Collateral
http://www.omdbapi.com/?apikey=7b298284&t=Congo
http://www.omdbapi.com/?apikey=7b298284&t=Lee+Daniels+The+Butler
http://www.omdbapi.com/?apikey=7b298284&t=Flightplan
http://www.omdbapi.com/?apikey=7b298284&t=Eraser
http://www.omdbapi.com/?apikey=7b298284&t=The+Girl+on+the+Train+(2016)
Couldn't find title:  The+Girl+on+the+Train+(2016)
http://www.omdbapi.com/?apikey=7b298284&t=The+Emoji+Movie
http://www.omdbapi.com/?apikey=7b298284&t=Forrest+Gump
http://www.omdbapi.com/?apikey=7b298284&t=Zero+Dark+Thirty
http://www.omdbapi.com/?apikey=7b298284&t=Mean+Girls
http://www.omdbapi.com/?apikey=7b298284&t=Race+to+Witch+Mountain
http://www.omdbapi.com/?apikey=7b298284&t=Contraband
http://www.omdbapi.com/?apikey=7b298284&t=The+Haunted+Mansion
http://www.omdbapi.com/?apikey=7b298284&t=The+Last+Samurai
http://www.omdbapi.com/?apikey=7b298284&t=TMNT
http://www.omdbapi.com/?apikey=7b298284&t=No+Good+Deed+(2014)
Couldn't find title:  No+Good+Deed+(2014)
http://www.omdbapi.com/?apikey=7b298284&t=Barbershop+2+Back+in+Business
http://www.omdbapi.com/?apikey=7b298284&t=Me,+Myself+and+Irene
Couldn't find title:  Me,+Myself+and+Irene
http://www.omdbapi.com/?apikey=7b298284&t=The+Princess+and+the+Frog
http://www.omdbapi.com/?apikey=7b298284&t=The+Addams+Family
http://www.omdbapi.com/?apikey=7b298284&t=Coach+Carter
http://www.omdbapi.com/?apikey=7b298284&t=Warcraft
http://www.omdbapi.com/?apikey=7b298284&t=Con+Air
http://www.omdbapi.com/?apikey=7b298284&t=Exodus+Gods+and+Kings
http://www.omdbapi.com/?apikey=7b298284&t=White+Noise
http://www.omdbapi.com/?apikey=7b298284&t=Tower+Heist
http://www.omdbapi.com/?apikey=7b298284&t=Fahrenheit+9/11
http://www.omdbapi.com/?apikey=7b298284&t=Captain+Underpants+The+First+Epic+Movie
http://www.omdbapi.com/?apikey=7b298284&t=Bad+Moms
http://www.omdbapi.com/?apikey=7b298284&t=Rise+of+the+Guardians
http://www.omdbapi.com/?apikey=7b298284&t=The+Fugitive
http://www.omdbapi.com/?apikey=7b298284&t=Diary+of+a+Wimpy+Kid+Rodrick+Rules
http://www.omdbapi.com/?apikey=7b298284&t=Fury+(2014)
Couldn't find title:  Fury+(2014)
http://www.omdbapi.com/?apikey=7b298284&t=Resident+Evil+Extinction
http://www.omdbapi.com/?apikey=7b298284&t=Tomb+Raider
http://www.omdbapi.com/?apikey=7b298284&t=Open+Season
http://www.omdbapi.com/?apikey=7b298284&t=Goosebumps
http://www.omdbapi.com/?apikey=7b298284&t=Dinner+for+Schmucks
http://www.omdbapi.com/?apikey=7b298284&t=The+Amityville+Horror+(2005)
Couldn't find title:  The+Amityville+Horror+(2005)
http://www.omdbapi.com/?apikey=7b298284&t=Be+Cool
http://www.omdbapi.com/?apikey=7b298284&t=Tyler+Perrys+I+Can+Do+Bad+All+By+Myself
Couldn't find title:  Tyler+Perrys+I+Can+Do+Bad+All+By+Myself
http://www.omdbapi.com/?apikey=7b298284&t=Once+Upon+a+Time+in+Mexico
http://www.omdbapi.com/?apikey=7b298284&t=Face/Off
http://www.omdbapi.com/?apikey=7b298284&t=The+Taking+of+Pelham+1+2+3
Couldn't find title:  The+Taking+of+Pelham+1+2+3
http://www.omdbapi.com/?apikey=7b298284&t=The+Polar+Express
http://www.omdbapi.com/?apikey=7b298284&t=Alvin+and+the+Chipmunks+Chipwrecked
http://www.omdbapi.com/?apikey=7b298284&t=Eragon
http://www.omdbapi.com/?apikey=7b298284&t=Michael+Jacksons+This+Is+It
Couldn't find title:  Michael+Jacksons+This+Is+It
http://www.omdbapi.com/?apikey=7b298284&t=Double+Jeopardy
http://www.omdbapi.com/?apikey=7b298284&t=The+Mask
http://www.omdbapi.com/?apikey=7b298284&t=Monster-in-Law
http://www.omdbapi.com/?apikey=7b298284&t=Eat+Pray+Love
http://www.omdbapi.com/?apikey=7b298284&t=Resident+Evil+Apocalypse
http://www.omdbapi.com/?apikey=7b298284&t=Return+of+the+Jedi
http://www.omdbapi.com/?apikey=7b298284&t=The+Haunting+in+Connecticut
http://www.omdbapi.com/?apikey=7b298284&t=The+Interpreter
http://www.omdbapi.com/?apikey=7b298284&t=Hidden+Figures
http://www.omdbapi.com/?apikey=7b298284&t=Man+on+Fire
http://www.omdbapi.com/?apikey=7b298284&t=Insidious+Chapter+3
http://www.omdbapi.com/?apikey=7b298284&t=Unstoppable
http://www.omdbapi.com/?apikey=7b298284&t=The+Time+Machine
http://www.omdbapi.com/?apikey=7b298284&t=Dick+Tracy
http://www.omdbapi.com/?apikey=7b298284&t=The+Mask+of+Zorro
http://www.omdbapi.com/?apikey=7b298284&t=Heaven+is+for+Real
http://www.omdbapi.com/?apikey=7b298284&t=Shallow+Hal
http://www.omdbapi.com/?apikey=7b298284&t=Life+of+Pi
http://www.omdbapi.com/?apikey=7b298284&t=The+Social+Network
http://www.omdbapi.com/?apikey=7b298284&t=Disturbia
http://www.omdbapi.com/?apikey=7b298284&t=Freaky+Friday
http://www.omdbapi.com/?apikey=7b298284&t=Die+Hard+With+A+Vengeance
http://www.omdbapi.com/?apikey=7b298284&t=Poseidon
http://www.omdbapi.com/?apikey=7b298284&t=Diary+of+a+Wimpy+Kid
http://www.omdbapi.com/?apikey=7b298284&t=Ghost+Rider+Spirit+of+Vengeance
http://www.omdbapi.com/?apikey=7b298284&t=Its+Complicated
Couldn't find title:  Its+Complicated
http://www.omdbapi.com/?apikey=7b298284&t=Kill+Bill+Vol.+1
http://www.omdbapi.com/?apikey=7b298284&t=Starship+Troopers
http://www.omdbapi.com/?apikey=7b298284&t=Chronicle+(2012)
Couldn't find title:  Chronicle+(2012)
http://www.omdbapi.com/?apikey=7b298284&t=Tyler+Perrys+Diary+of+a+Mad+Black+Woman
Couldn't find title:  Tyler+Perrys+Diary+of+a+Mad+Black+Woman
http://www.omdbapi.com/?apikey=7b298284&t=Inspector+Gadget
http://www.omdbapi.com/?apikey=7b298284&t=Neighbors+2+Sorority+Rising
http://www.omdbapi.com/?apikey=7b298284&t=Underworld

http://www.omdbapi.com/?apikey=7b298284&t=Die+Hard+2+Die+Harder
Couldn't find title:  Die+Hard+2+Die+Harder
http://www.omdbapi.com/?apikey=7b298284&t=Texas+Chainsaw+3D
http://www.omdbapi.com/?apikey=7b298284&t=Shaft
http://www.omdbapi.com/?apikey=7b298284&t=Lights+Out
http://www.omdbapi.com/?apikey=7b298284&t=RoboCop+(2014)
Couldn't find title:  RoboCop+(2014)
http://www.omdbapi.com/?apikey=7b298284&t=Fools+Gold
http://www.omdbapi.com/?apikey=7b298284&t=Tammy
http://www.omdbapi.com/?apikey=7b298284&t=You,+Me+and+Dupree
http://www.omdbapi.com/?apikey=7b298284&t=Petes+Dragon+(2016)
Couldn't find title:  Petes+Dragon+(2016)
http://www.omdbapi.com/?apikey=7b298284&t=American+Reunion
http://www.omdbapi.com/?apikey=7b298284&t=Hercules
http://www.omdbapi.com/?apikey=7b298284&t=The+40-Year-Old+Virgin
http://www.omdbapi.com/?apikey=7b298284&t=The+Stepford+Wives
http://www.omdbapi.com/?apikey=7b298284&t=The+Hitmans+Bodyguard
Couldn't find title:  The+Hitmans+Bodyguard
http://www.omdbapi.com/?apikey=7b298284&t=Ice+Age+Collision+Course
http://www.omdbapi.com/?apikey=7b298284&t=Tyler+Perrys+Why+Did+I+Get+Married?
Couldn't find title:  Tyler+Perrys+Why+Did+I+Get+Married?
http://www.omdbapi.com/?apikey=7b298284&t=Storks
http://www.omdbapi.com/?apikey=7b298284&t=Happy+Feet+Two
http://www.omdbapi.com/?apikey=7b298284&t=Waterworld
http://www.omdbapi.com/?apikey=7b298284&t=The+Adjustment+Bureau
http://www.omdbapi.com/?apikey=7b298284&t=Bride+Wars
http://www.omdbapi.com/?apikey=7b298284&t=13+Going+on+30
http://www.omdbapi.com/?apikey=7b298284&t=Resident+Evil+Retribution
http://www.omdbapi.com/?apikey=7b298284&t=Lincoln
http://www.omdbapi.com/?apikey=7b298284&t=Law+Abiding+Citizen
http://www.omdbapi.com/?apikey=7b298284&t=The+Forgotten
http://www.omdbapi.com/?apikey=7b298284&t=Journey+to+the+Center+of+the+Earth
http://www.omdbapi.com/?apikey=7b298284&t=The+Strangers
http://www.omdbapi.com/?apikey=7b298284&t=Insomnia
http://www.omdbapi.com/?apikey=7b298284&t=The+Woman+in+Black
http://www.omdbapi.com/?apikey=7b298284&t=The+Grudge+2
http://www.omdbapi.com/?apikey=7b298284&t=Prom+Night+(2008)
Couldn't find title:  Prom+Night+(2008)
http://www.omdbapi.com/?apikey=7b298284&t=Guess+Who
http://www.omdbapi.com/?apikey=7b298284&t=The+Wedding+Ringer
http://www.omdbapi.com/?apikey=7b298284&t=Contact
http://www.omdbapi.com/?apikey=7b298284&t=Blockers
http://www.omdbapi.com/?apikey=7b298284&t=Takers
http://www.omdbapi.com/?apikey=7b298284&t=Scary+Movie+2
http://www.omdbapi.com/?apikey=7b298284&t=Mrs.+Doubtfire
http://www.omdbapi.com/?apikey=7b298284&t=Rocky+IV
http://www.omdbapi.com/?apikey=7b298284&t=Pitch+Perfect+3
http://www.omdbapi.com/?apikey=7b298284&t=102+Dalmatians
http://www.omdbapi.com/?apikey=7b298284&t=Ouija
http://www.omdbapi.com/?apikey=7b298284&t=Kick-Ass
http://www.omdbapi.com/?apikey=7b298284&t=The+Unborn+(2009)
Couldn't find title:  The+Unborn+(2009)
http://www.omdbapi.com/?apikey=7b298284&t=The+Cable+Guy
http://www.omdbapi.com/?apikey=7b298284&t=Spawn
http://www.omdbapi.com/?apikey=7b298284&t=Hansel+and+Gretel+Witch+Hunters
Couldn't find title:  Hansel+and+Gretel+Witch+Hunters
http://www.omdbapi.com/?apikey=7b298284&t=White+Chicks
http://www.omdbapi.com/?apikey=7b298284&t=The+Grey
http://www.omdbapi.com/?apikey=7b298284&t=The+Benchwarmers
http://www.omdbapi.com/?apikey=7b298284&t=No+Strings+Attached
http://www.omdbapi.com/?apikey=7b298284&t=Kingdom+of+Heaven
http://www.omdbapi.com/?apikey=7b298284&t=Paranormal+Activity
http://www.omdbapi.com/?apikey=7b298284&t=The+Animal
http://www.omdbapi.com/?apikey=7b298284&t=Year+One
http://www.omdbapi.com/?apikey=7b298284&t=Pokemon+The+Movie+2000
http://www.omdbapi.com/?apikey=7b298284&t=Hostel
http://www.omdbapi.com/?apikey=7b298284&t=U-571
http://www.omdbapi.com/?apikey=7b298284&t=The+Santa+Clause+3+The+Escape+Clause
http://www.omdbapi.com/?apikey=7b298284&t=Moneyball
http://www.omdbapi.com/?apikey=7b298284&t=Another+48+HRS.
http://www.omdbapi.com/?apikey=7b298284&t=Argo
http://www.omdbapi.com/?apikey=7b298284&t=The+Italian+Job
in except
http://www.omdbapi.com/?apikey=7b298284&t=I+Am+Number+Four
http://www.omdbapi.com/?apikey=7b298284&t=Alien+3
http://www.omdbapi.com/?apikey=7b298284&t=The+Huntsman+Winters+War
Couldn't find title:  The+Huntsman+Winters+War
http://www.omdbapi.com/?apikey=7b298284&t=The+Nut+Job
http://www.omdbapi.com/?apikey=7b298284&t=Brother+Bear
http://www.omdbapi.com/?apikey=7b298284&t=The+Bucket+List
http://www.omdbapi.com/?apikey=7b298284&t=The+Post
http://www.omdbapi.com/?apikey=7b298284&t=The+Santa+Clause
http://www.omdbapi.com/?apikey=7b298284&t=Conspiracy+Theory
http://www.omdbapi.com/?apikey=7b298284&t=Aladdin
http://www.omdbapi.com/?apikey=7b298284&t=Final+Destination+3
http://www.omdbapi.com/?apikey=7b298284&t=Tim+Burtons+Corpse+Bride
Couldn't find title:  Tim+Burtons+Corpse+Bride
http://www.omdbapi.com/?apikey=7b298284&t=Stepmom
http://www.omdbapi.com/?apikey=7b298284&t=Burn+After+Reading
http://www.omdbapi.com/?apikey=7b298284&t=American+Hustle
http://www.omdbapi.com/?apikey=7b298284&t=Back+to+the+Future+Part+III
http://www.omdbapi.com/?apikey=7b298284&t=Date+Movie
http://www.omdbapi.com/?apikey=7b298284&t=The+Terminal
http://www.omdbapi.com/?apikey=7b298284&t=Riddick
http://www.omdbapi.com/?apikey=7b298284&t=Boogeyman
http://www.omdbapi.com/?apikey=7b298284&t=The+Score
http://www.omdbapi.com/?apikey=7b298284&t=Sicario+Day+of+the+Soldado
http://www.omdbapi.com/?apikey=7b298284&t=The+Spiderwick+Chronicles
http://www.omdbapi.com/?apikey=7b298284&t=The+First+Wives+Club
http://www.omdbapi.com/?apikey=7b298284&t=Step+Up+2+the+Streets
http://www.omdbapi.com/?apikey=7b298284&t=Limitless
http://www.omdbapi.com/?apikey=7b298284&t=Land+of+the+Lost
http://www.omdbapi.com/?apikey=7b298284&t=Hidalgo
http://www.omdbapi.com/?apikey=7b298284&t=Flushed+Away
http://www.omdbapi.com/?apikey=7b298284&t=Red+Tails
http://www.omdbapi.com/?apikey=7b298284&t=World+Trade+Center
http://www.omdbapi.com/?apikey=7b298284&t=Me+Before+You
http://www.omdbapi.com/?apikey=7b298284&t=Maid+in+Manhattan
http://www.omdbapi.com/?apikey=7b298284&t=Scream+4
http://www.omdbapi.com/?apikey=7b298284&t=Focus+(2015)
http://www.omdbapi.com/?apikey=7b298284&t=Truth+or+Dare
http://www.omdbapi.com/?apikey=7b298284&t=The+Time+Travelers+Wife
Couldn't find title:  The+Time+Travelers+Wife
http://www.omdbapi.com/?apikey=7b298284&t=Jurassic+Park+3D
http://www.omdbapi.com/?apikey=7b298284&t=Epic+Movie
http://www.omdbapi.com/?apikey=7b298284&t=Are+We+There+Yet?
http://www.omdbapi.com/?apikey=7b298284&t=Meet+the+Spartans
http://www.omdbapi.com/?apikey=7b298284&t=Baywatch
http://www.omdbapi.com/?apikey=7b298284&t=Dantes+Peak
Couldn't find title:  Dantes+Peak
http://www.omdbapi.com/?apikey=7b298284&t=Youve+Got+Mail
Couldn't find title:  Youve+Got+Mail
http://www.omdbapi.com/?apikey=7b298284&t=Indecent+Proposal
http://www.omdbapi.com/?apikey=7b298284&t=Alexander+and+the+Terrible,+Horrible,+No+Good,+Very+Bad+Day
http://www.omdbapi.com/?apikey=7b298284&t=Stigmata
http://www.omdbapi.com/?apikey=7b298284&t=Saw
http://www.omdbapi.com/?apikey=7b298284&t=The+Birdcage
http://www.omdbapi.com/?apikey=7b298284&t=Secret+Window
http://www.omdbapi.com/?apikey=7b298284&t=Cop+Out
http://www.omdbapi.com/?apikey=7b298284&t=Rambo
http://www.omdbapi.com/?apikey=7b298284&t=Bowfinger
http://www.omdbapi.com/?apikey=7b298284&t=Lady+in+the+Water
http://www.omdbapi.com/?apikey=7b298284&t=Final+Destination+5
http://www.omdbapi.com/?apikey=7b298284&t=The+Green+Mile
http://www.omdbapi.com/?apikey=7b298284&t=Romeo+Must+Die
http://www.omdbapi.com/?apikey=7b298284&t=Sinister
http://www.omdbapi.com/?apikey=7b298284&t=The+Guardian
http://www.omdbapi.com/?apikey=7b298284&t=Hero
http://www.omdbapi.com/?apikey=7b298284&t=Life+of+the+Party
http://www.omdbapi.com/?apikey=7b298284&t=My+Big+Fat+Greek+Wedding+2
http://www.omdbapi.com/?apikey=7b298284&t=Lets+Be+Cops
Couldn't find title:  Lets+Be+Cops
http://www.omdbapi.com/?apikey=7b298284&t=I+Love+You,+Man
http://www.omdbapi.com/?apikey=7b298284&t=Forgetting+Sarah+Marshall
http://www.omdbapi.com/?apikey=7b298284&t=First+Sunday
http://www.omdbapi.com/?apikey=7b298284&t=Resident+Evil
http://www.omdbapi.com/?apikey=7b298284&t=Surfs+Up
http://www.omdbapi.com/?apikey=7b298284&t=Breaking+In+(2018)
Couldn't find title:  Breaking+In+(2018)
http://www.omdbapi.com/?apikey=7b298284&t=Just+Married

http://www.omdbapi.com/?apikey=7b298284&t=The+Smurfs+2
http://www.omdbapi.com/?apikey=7b298284&t=Old+School
http://www.omdbapi.com/?apikey=7b298284&t=Michael
http://www.omdbapi.com/?apikey=7b298284&t=Baby+Mama
http://www.omdbapi.com/?apikey=7b298284&t=This+Means+War
http://www.omdbapi.com/?apikey=7b298284&t=Tyler+Perrys+The+Family+That+Preys
Couldn't find title:  Tyler+Perrys+The+Family+That+Preys
http://www.omdbapi.com/?apikey=7b298284&t=Star+Trek+V+The+Final+Frontier
http://www.omdbapi.com/?apikey=7b298284&t=Bring+It+On
http://www.omdbapi.com/?apikey=7b298284&t=Into+The+Storm
http://www.omdbapi.com/?apikey=7b298284&t=Coyote+Ugly
http://www.omdbapi.com/?apikey=7b298284&t=Titanic+3D
Couldn't find title:  Titanic+3D
http://www.omdbapi.com/?apikey=7b298284&t=The+Boxtrolls
http://www.omdbapi.com/?apikey=7b298284&t=Down+to+Earth
http://www.omdbapi.com/?apikey=7b298284&t=Maverick
http://www.omdbapi.com/?apikey=7b298284&t=The+Client
http://www.omdbapi.com/?apikey=7b298284&t=Tyler+Perrys+Acrimony
Couldn't find title:  Tyler+Perrys+Acrimony
http://www.omdbapi.com/?apikey=7b298284&t=The+Hunt+for+Red+October
http://www.omdbapi.com/?apikey=7b298284&t=The+Kingdom
http://www.omdbapi.com/?apikey=7b298284&t=Changing+Lanes
http://www.omdbapi.com/?apikey=7b298284&t=I+Can+Only+Imagine
http://www.omdbapi.com/?apikey=7b298284&t=Night+at+the+Museum+Secret+of+the+Tomb
http://www.omdbapi.com/?apikey=7b298284&t=Home+Alone
http://www.omdbapi.com/?apikey=7b298284&t=Blade
http://www.omdbapi.com/?apikey=7b298284&t=Gangster+Squad
http://www.omdbapi.com/?apikey=7b298284&t=The+Butterfly+Effect
http://www.omdbapi.com/?apikey=7b298284&t=The+Fifth+Element
http://www.omdbapi.com/?apikey=7b298284&t=Hotel+for+Dogs
http://www.omdbapi.com/?apikey=7b298284&t=Game+Night
http://www.omdbapi.com/?apikey=7b298284&t=Old+Dogs
http://www.omdbapi.com/?apikey=7b298284&t=Star+Trek+IV+The+Voyage+Home
http://www.omdbapi.com/?apikey=7b298284&t=Red+Sparrow
http://www.omdbapi.com/?apikey=7b298284&t=Water+for+Elephants
http://www.omdbapi.com/?apikey=7b298284&t=A+Million+Ways+to+Die+in+the+West
http://www.omdbapi.com/?apikey=7b298284&t=American+Made
http://www.omdbapi.com/?apikey=7b298284&t=A+Bad+Moms+Christmas
http://www.omdbapi.com/?apikey=7b298284&t=Priest
http://www.omdbapi.com/?apikey=7b298284&t=Tag
http://www.omdbapi.com/?apikey=7b298284&t=Dangerous+Minds
http://www.omdbapi.com/?apikey=7b298284&t=The+Boy+Next+Door
http://www.omdbapi.com/?apikey=7b298284&t=Harold+and+Kumar+Escape+from+Guantanamo+Bay
Couldn't find title:  Harold+and+Kumar+Escape+from+Guantanamo+Bay
http://www.omdbapi.com/?apikey=7b298284&t=Surrogates
http://www.omdbapi.com/?apikey=7b298284&t=Passengers+(2016)
Couldn't find title:  Passengers+(2016)
http://www.omdbapi.com/?apikey=7b298284&t=Inferno
http://www.omdbapi.com/?apikey=7b298284&t=Seven+Pounds
http://www.omdbapi.com/?apikey=7b298284&t=Pitch+Perfect
http://www.omdbapi.com/?apikey=7b298284&t=American+Assassin
http://www.omdbapi.com/?apikey=7b298284&t=A+Time+to+Kill
http://www.omdbapi.com/?apikey=7b298284&t=Miracles+from+Heaven
http://www.omdbapi.com/?apikey=7b298284&t=Source+Code
http://www.omdbapi.com/?apikey=7b298284&t=Australia
http://www.omdbapi.com/?apikey=7b298284&t=The+Rite
http://www.omdbapi.com/?apikey=7b298284&t=Money+Monster
http://www.omdbapi.com/?apikey=7b298284&t=Made+of+Honor
http://www.omdbapi.com/?apikey=7b298284&t=The+Cabin+in+the+Woods
http://www.omdbapi.com/?apikey=7b298284&t=The+Messengers
http://www.omdbapi.com/?apikey=7b298284&t=Overboard+(2018)
Couldn't find title:  Overboard+(2018)
http://www.omdbapi.com/?apikey=7b298284&t=Ali
http://www.omdbapi.com/?apikey=7b298284&t=War+Dogs
http://www.omdbapi.com/?apikey=7b298284&t=Vacation
http://www.omdbapi.com/?apikey=7b298284&t=Absolute+Power
http://www.omdbapi.com/?apikey=7b298284&t=Hope+Springs
http://www.omdbapi.com/?apikey=7b298284&t=Smokin+Aces
http://www.omdbapi.com/?apikey=7b298284&t=Sky+High
http://www.omdbapi.com/?apikey=7b298284&t=Diary+of+a+Wimpy+Kid+Dog+Days
http://www.omdbapi.com/?apikey=7b298284&t=Private+Parts
http://www.omdbapi.com/?apikey=7b298284&t=Star+Wars+The+Clone+Wars
http://www.omdbapi.com/?apikey=7b298284&t=The+Number+23
http://www.omdbapi.com/?apikey=7b298284&t=The+Thomas+Crown+Affair
http://www.omdbapi.com/?apikey=7b298284&t=Volcano
http://www.omdbapi.com/?apikey=7b298284&t=Cold+Mountain
http://www.omdbapi.com/?apikey=7b298284&t=Crossroads
http://www.omdbapi.com/?apikey=7b298284&t=Life+as+We+Know+It
http://www.omdbapi.com/?apikey=7b298284&t=Nanny+McPhee
http://www.omdbapi.com/?apikey=7b298284&t=Next+Friday
http://www.omdbapi.com/?apikey=7b298284&t=Sphere
http://www.omdbapi.com/?apikey=7b298284&t=Gridiron+Gang
http://www.omdbapi.com/?apikey=7b298284&t=Percy+Jackson+Sea+of+Monsters
http://www.omdbapi.com/?apikey=7b298284&t=National+Security
http://www.omdbapi.com/?apikey=7b298284&t=The+Sentinel
http://www.omdbapi.com/?apikey=7b298284&t=Star+Trek+II+The+Wrath+of+Khan
http://www.omdbapi.com/?apikey=7b298284&t=The+Game
http://www.omdbapi.com/?apikey=7b298284&t=Snow+Day
http://www.omdbapi.com/?apikey=7b298284&t=The+Specialist
http://www.omdbapi.com/?apikey=7b298284&t=In+Good+Company
http://www.omdbapi.com/?apikey=7b298284&t=Alvin+and+the+Chipmunks+The+Road+Chip
http://www.omdbapi.com/?apikey=7b298284&t=Blended
http://www.omdbapi.com/?apikey=7b298284&t=John+Tucker+Must+Die
http://www.omdbapi.com/?apikey=7b298284&t=The+Devils+Own
Couldn't find title:  The+Devils+Own
http://www.omdbapi.com/?apikey=7b298284&t=Honey,+I+Shrunk+the+Kids
http://www.omdbapi.com/?apikey=7b298284&t=Are+We+Done+Yet?
http://www.omdbapi.com/?apikey=7b298284&t=E.T.+(20th+Anniversary)
Couldn't find title:  E.T.+(20th+Anniversary)
http://www.omdbapi.com/?apikey=7b298284&t=Quarantine
http://www.omdbapi.com/?apikey=7b298284&t=Hope+Floats
http://www.omdbapi.com/?apikey=7b298284&t=Blue+Crush
http://www.omdbapi.com/?apikey=7b298284&t=Scary+Movie+5
http://www.omdbapi.com/?apikey=7b298284&t=Gods+of+Egypt
http://www.omdbapi.com/?apikey=7b298284&t=The+Last+House+on+the+Left+(2009)
Couldn't find title:  The+Last+House+on+the+Left+(2009)
http://www.omdbapi.com/?apikey=7b298284&t=Addams+Family+Values
http://www.omdbapi.com/?apikey=7b298284&t=Anastasia
http://www.omdbapi.com/?apikey=7b298284&t=Dreamgirls
http://www.omdbapi.com/?apikey=7b298284&t=Agent+Cody+Banks
http://www.omdbapi.com/?apikey=7b298284&t=Open+Range
http://www.omdbapi.com/?apikey=7b298284&t=Miss+Congeniality+2+Armed+and+Fabulous
Couldn't find title:  Miss+Congeniality+2+Armed+and+Fabulous
http://www.omdbapi.com/?apikey=7b298284&t=Domestic+Disturbance
http://www.omdbapi.com/?apikey=7b298284&t=The+Heartbreak+Kid
http://www.omdbapi.com/?apikey=7b298284&t=High+Crimes
http://www.omdbapi.com/?apikey=7b298284&t=Seven
http://www.omdbapi.com/?apikey=7b298284&t=Hot+Pursuit
http://www.omdbapi.com/?apikey=7b298284&t=The+Siege
http://www.omdbapi.com/?apikey=7b298284&t=Racing+Stripes
http://www.omdbapi.com/?apikey=7b298284&t=Home+on+the+Range
http://www.omdbapi.com/?apikey=7b298284&t=Dude,+Wheres+My+Car?
Couldn't find title:  Dude,+Wheres+My+Car?
http://www.omdbapi.com/?apikey=7b298284&t=Snakes+on+a+Plane
http://www.omdbapi.com/?apikey=7b298284&t=Theres+Something+About+Mary
Couldn't find title:  Theres+Something+About+Mary
http://www.omdbapi.com/?apikey=7b298284&t=A+League+of+Their+Own
http://www.omdbapi.com/?apikey=7b298284&t=The+Whole+Nine+Yards
http://www.omdbapi.com/?apikey=7b298284&t=Moulin+Rouge!
http://www.omdbapi.com/?apikey=7b298284&t=Geostorm
http://www.omdbapi.com/?apikey=7b298284&t=The+Commuter
http://www.omdbapi.com/?apikey=7b298284&t=Underworld+Blood+Wars
http://www.omdbapi.com/?apikey=7b298284&t=Good+Luck+Chuck
http://www.omdbapi.com/?apikey=7b298284&t=Firewall
http://www.omdbapi.com/?apikey=7b298284&t=Resident+Evil+The+Final+Chapter
http://www.omdbapi.com/?apikey=7b298284&t=College+Road+Trip
http://www.omdbapi.com/?apikey=7b298284&t=Hereditary
http://www.omdbapi.com/?apikey=7b298284&t=Hanging+Up
http://www.omdbapi.com/?apikey=7b298284&t=Letters+to+Juliet
http://www.omdbapi.com/?apikey=7b298284&t=Hall+Pass
http://www.omdbapi.com/?apikey=7b298284&t=Without+a+Paddle
http://www.omdbapi.com/?apikey=7b298284&t=Cop+Land
http://www.omdbapi.com/?apikey=7b298284&t=The+Wedding+Planner
http://www.omdbapi.com/?apikey=7b298284&t=Paycheck
http://www.omdbapi.com/?apikey=7b298284&t=Thats+My+Boy

Couldn't find title:  Thats+My+Boy
http://www.omdbapi.com/?apikey=7b298284&t=Jaws+3-D
http://www.omdbapi.com/?apikey=7b298284&t=The+Man+From+U.N.C.L.E.
http://www.omdbapi.com/?apikey=7b298284&t=Outbreak
http://www.omdbapi.com/?apikey=7b298284&t=Nights+in+Rodanthe
http://www.omdbapi.com/?apikey=7b298284&t=Stranger+Than+Fiction
http://www.omdbapi.com/?apikey=7b298284&t=Evolution
http://www.omdbapi.com/?apikey=7b298284&t=Superman+III
http://www.omdbapi.com/?apikey=7b298284&t=Brooklyns+Finest
Couldn't find title:  Brooklyns+Finest
http://www.omdbapi.com/?apikey=7b298284&t=Chappie
http://www.omdbapi.com/?apikey=7b298284&t=Kick-Ass+2
http://www.omdbapi.com/?apikey=7b298284&t=Jersey+Boys
http://www.omdbapi.com/?apikey=7b298284&t=Kiss+of+the+Dragon
http://www.omdbapi.com/?apikey=7b298284&t=Radio
http://www.omdbapi.com/?apikey=7b298284&t=Stealth
http://www.omdbapi.com/?apikey=7b298284&t=Everest+(2015)
Couldn't find title:  Everest+(2015)
http://www.omdbapi.com/?apikey=7b298284&t=Book+of+Shadows+Blair+Witch+2
http://www.omdbapi.com/?apikey=7b298284&t=Kiss+the+Girls
http://www.omdbapi.com/?apikey=7b298284&t=Nims+Island
Couldn't find title:  Nims+Island
http://www.omdbapi.com/?apikey=7b298284&t=The+Age+of+Adaline
http://www.omdbapi.com/?apikey=7b298284&t=Hitman
http://www.omdbapi.com/?apikey=7b298284&t=The+American
http://www.omdbapi.com/?apikey=7b298284&t=Snitch
http://www.omdbapi.com/?apikey=7b298284&t=Crimson+Peak
http://www.omdbapi.com/?apikey=7b298284&t=The+Foreigner
http://www.omdbapi.com/?apikey=7b298284&t=Jeepers+Creepers
http://www.omdbapi.com/?apikey=7b298284&t=Matchstick+Men
http://www.omdbapi.com/?apikey=7b298284&t=Bandits
http://www.omdbapi.com/?apikey=7b298284&t=For+Love+of+the+Game
http://www.omdbapi.com/?apikey=7b298284&t=City+Slickers
http://www.omdbapi.com/?apikey=7b298284&t=Cruel+Intentions
http://www.omdbapi.com/?apikey=7b298284&t=The+Longest+Ride
http://www.omdbapi.com/?apikey=7b298284&t=Random+Hearts

In [29]:
weekend_box.to_csv('before_imdb.csv')

In [31]:
weekend_box.head(100)

,Title,Studio,Opening,Date,Director,Budget,imdbID,month,year,Actor,Genre,Writer
6,Avengers: Infinity War,BV,"$257,698,183",4/27/2018,"Anthony Russo, Joe Russo",,tt4154756,4,2018,"Robert Downey Jr., Chris Hemsworth, Mark Ruffa...","Action, Adventure, Fantasy","Christopher Markus (screenplay by), Stephen Mc..."
7,Star Wars: The Force Awakens,BV,"$247,966,675",12/18/2015,J.J. Abrams,,tt2488496,12,2015,"Harrison Ford, Mark Hamill, Carrie Fisher, Ada...","Action, Adventure, Fantasy","Lawrence Kasdan, J.J. Abrams, Michael Arndt, G..."
8,Star Wars: The Last Jedi,BV,"$220,009,584",12/15/2017,Rian Johnson,,tt2527336,12,2017,"Mark Hamill, Carrie Fisher, Adam Driver, Daisy...","Action, Adventure, Fantasy","Rian Johnson, George Lucas (based on character..."
9,Jurassic World,Uni.,"$208,806,270",6/12/2015,Colin Trevorrow,,tt0369610,6,2015,"Chris Pratt, Bryce Dallas Howard, Irrfan Khan,...","Action, Adventure, Sci-Fi","Rick Jaffa (screenplay by), Amanda Silver (scr..."
10,Marvel's The Avengers,BV,"$207,438,708",5/4/2012,,,,5,2012,,,
11,Black Panther,BV,"$202,003,951",2/16/2018,Ryan Coogler,,tt1825683,2,2018,"Chadwick Boseman, Michael B. Jordan, Lupita Ny...","Action, Adventure, Sci-Fi","Ryan Coogler, Joe Robert Cole, Stan Lee (based..."
12,Avengers: Age of Ultron,BV,"$191,271,109",5/1/2015,Joss Whedon,,tt2395427,5,2015,"Robert Downey Jr., Chris Hemsworth, Mark Ruffa...","Action, Adventure, Sci-Fi","Joss Whedon, Stan Lee (based on the Marvel com..."
13,Incredibles 2,BV,"$182,687,905",6/15/2018,Brad Bird,,tt3606756,6,2018,"Craig T. Nelson, Holly Hunter, Sarah Vowell, H...","Animation, Action, Adventure",Brad Bird
14,Captain America: Civil War,BV,"$179,139,142",5/6/2016,"Anthony Russo, Joe Russo",,tt3498820,5,2016,"Chris Evans, Robert Downey Jr., Scarlett Johan...","Action, Adventure, Sci-Fi","Christopher Markus (screenplay by), Stephen Mc..."
15,Beauty and the Beast (2017),BV,"$174,750,616",3/17/2017,,,,3,2017,,,
16,Iron Man 3,BV,"$174,144,585",5/3/2013,Shane Black,,tt1300854,5,2013,"Robert Downey Jr., Gwyneth Paltrow, Don Cheadl...","Action, Adventure, Sci-Fi","Drew Pearce (screenplay by), Shane Black (scre..."
17,Harry Potter and the Deathly Hallows Part 2,WB,"$169,189,427",7/15/2011,David Yates,,tt1201607,7,2011,"Ralph Fiennes, Michael Gambon, Alan Rickman, D...","Adventure, Drama, Fantasy","Steve Kloves (screenplay), J.K. Rowling (novel)"
18,Batman v Superman: Dawn of Justice,WB,"$166,007,347",3/25/2016,Zack Snyder,,tt2975590,3,2016,"Ben Affleck, Henry Cavill, Amy Adams, Jesse Ei...","Action, Adventure, Fantasy","Chris Terrio, David S. Goyer, Bob Kane (Batman..."
19,The Dark Knight Rises,WB,"$160,887,295",7/20/2012,Christopher Nolan,,tt1345836,7,2012,"Christian Bale, Gary Oldman, Tom Hardy, Joseph...","Action, Thriller","Jonathan Nolan (screenplay), Christopher Nolan..."
21,The Hunger Games: Catching Fire,LGF,"$158,074,286",11/22/2013,Francis Lawrence,,tt1951264,11,2013,"Jennifer Lawrence, Liam Hemsworth, Jack Quaid,...","Action, Adventure, Mystery","Simon Beaufoy (screenplay), Michael Arndt (scr..."
22,Rogue One: A Star Wars Story,BV,"$155,081,681",12/16/2016,Gareth Edwards,,tt3748528,12,2016,"Felicity Jones, Diego Luna, Alan Tudyk, Donnie...","Action, Adventure, Sci-Fi","Chris Weitz (screenplay by), Tony Gilroy (scre..."
23,The Hunger Games,LGF,"$152,535,747",3/23/2012,Gary Ross,,tt1392170,3,2012,"Stanley Tucci, Wes Bentley, Jennifer Lawrence,...","Adventure, Sci-Fi, Thriller","Gary Ross (screenplay), Suzanne Collins (scree..."
25,Jurassic World: Fallen Kingdom,Uni.,"$148,024,610",6/22/2018,J.A. Bayona,,tt4881806,6,2018,"Chris Pratt, Bryce Dallas Howard, Rafe Spall, ...","Action, Adventure, Sci-Fi","Derek Connolly, Colin Trevorrow, Michael Crich..."
26,Furious 7,Uni.,"$147,187,040",4/3/2015,James Wan,,tt2820852,4,2015,"Vin Diesel, Paul Walker, Jason Statham, Michel...","Action, Crime, Thriller","Chris Morgan, Gary Scott Thompson (characters)"
27,Guardians of the Galaxy Vol. 2,BV,"$146,510,104",5/5/2017,James Gunn,,tt3896198,5,2017,"Chris Pratt, Zoe Saldana, Dave Bautista, Vin D...","Action, Adventure, Sci-Fi","James Gunn, Dan Abnett (based on the Marvel co..."
29,The Twilight Saga: Breaking Dawn Part 2,LG/S,"$141,067,634",11/16/2012,Bill Condon,,tt1673434,11,2012,"Kristen Stewart, Robert Pattinson, Taylor Laut...","Adventure, Drama, Fantasy","Melissa Rosenberg (screenplay), Stephenie Meye..."
30,The Twilight Saga: Breaking Dawn Part 1,Sum.,"$138,122,261",11/18/2011,N/A,,tt2395475,11,2011,Juley Ross,Short,N/A
32,Finding Dory,BV,"$135,060,273",6/17/2016,,,,6,2016,,,
33,Suicide Squad,WB,"$133,682,248",8/5/2016,,,,8,2016,,,
34,Deadpool,Fox,"$132,434,639",2/12/2016,,,,2,2016,,,
35,Iron Man 2,Par.,"$128,122,480",5/7/2010,,,,5,2010,,,
36,Deadpool 2,Fox,"$125,507,153",5/18/2018,,,,5,2018,,,
37,Harry Potter and the Deathly Hallows Part 1,WB,"$125,017,372",11/19/2010,,,,11,2010,,,
38,It,WB (NL),"$123,403,419",9/8/2017,,,,9,2017,,,
39,Thor: Ragnarok,BV,"$122,744,989",11/3/2017,,,,11,2017,,,
...,...,...,...,...,...,...,...,...,...,...,...,...
111,Shrek Forever After,P/DW,"$70,838,207",5/21/2010,,,,5,2010,,,
114,Spectre,Sony,"$70,403,148",11/6/2015,,,,11,2015,,,
116,Dr. Seuss' The Lorax,Uni.,"$70,217,070",3/2/2012,,,,3,2012,,,
117,Star Trek Into Darkness,Par.,"$70,165,559",5/16/2013,,,,5,2013,,,
119,Maleficent,BV,"$69,431,298",5/30/2014,,,,5,2014,,,
121,Pitch Perfect 2,Uni.,"$69,216,890",5/15/2015,,,,5,2015,,,
122,The LEGO Movie,WB,"$69,050,279",2/7/2014,,,,2,2014,,,
129,Cinderella (2015),BV,"$67,877,361",3/13/2015,,,,3,2015,,,
132,Frozen,BV,"$67,391,326",11/27/2013,,,,11,2013,,,
133,World War Z,Par.,"$66,411,834",6/21/2013,,,,6,2013,,,
134,Brave,BV,"$66,323,594",6/22/2012,,,,6,2012,,,
135,Cars 2,BV,"$66,135,507",6/24/2011,,,,6,2011,,,
136,X-Men: Apocalypse,Fox,"$65,769,562",5/27/2016,,,,5,2016,,,
137,Thor,Par.,"$65,723,338",5/6/2011,,,,5,2011,,,
138,Teenage Mutant Ninja Turtles (2014),Par.,"$65,575,105",8/8/2014,,,,8,2014,,,
141,Captain America: The First Avenger,Par.,"$65,058,524",7/22/2011,,,,7,2011,,,
143,The Twilight Saga: Eclipse,Sum.,"$64,832,191",6/30/2010,,,,6,2010,,,
147,Pirates of the Caribbean: Dead Men Tell No Tales,BV,"$62,983,253",5/26/2017,,,,5,2017,,,
148,Inception,WB,"$62,785,337",7/16/2010,,,,7,2010,,,
154,The Amazing Spider-Man,Sony,"$62,004,688",7/3/2012,,,,7,2012,,,
155,Clash of the Titans (2010),WB,"$61,235,105",4/2/2010,,,,4,2010,,,
156,Kong: Skull Island,WB,"$61,025,472",3/10/2017,,,,3,2017,,,
157,Madagascar 3: Europe's Most Wanted,P/DW,"$60,316,738",6/8/2012,,,,6,2012,,,
159,Straight Outta Compton,Uni.,"$60,200,180",8/14/2015,,,,8,2015,,,
163,Star Trek Beyond,Par.,"$59,253,211",7/22/2016,,,,7,2016,,,
164,Jason Bourne,Uni.,"$59,215,365",7/29/2016,,,,7,2016,,,
170,Ant-Man,BV,"$57,225,526",7/17/2015,,,,7,2015,,,
171,22 Jump Street,Sony,"$57,071,445",6/13/2014,,,,6,2014,,,
173,Moana,BV,"$56,631,401",11/23/2016,,,,11,2016,,,
174,Despicable Me,Uni.,"$56,397,125",7/9/2010,,,,7,2010,,,

In [33]:
imdb = 'https://www.imdb.com/title/'
for index, row in weekend_box.head().iterrows():
    imdbID = row['imdbID']
    page = imdb + imdbID

    try:
        response = req.get(page)
        soup = BeautifulSoup(response.text, 'html.parser')
        txt_block = soup.find_all('div', class_="txt-block")
        budget_block = txt_block[9]
        budget = budget_block.text
        budget = budget.strip()
        budget = budget.split('\n')[0]
        budget = budget.split(':')[1]
        weekend_box.set_value(index, 'Budget', budget)
    except:
        continue

In [34]:
weekend_box

,Title,Studio,Opening,Date,Director,Budget,imdbID,month,year,Actor,Genre,Writer
6,Avengers: Infinity War,BV,"$257,698,183",4/27/2018,Scott Stewart,"$60,000,000",tt0822847,4,2018,"Paul Bettany, Karl Urban, Cam Gigandet, Maggie Q","Action, Fantasy, Horror","Cory Goodman, Min-Woo Hyung (graphic novel ser..."
7,Star Wars: The Force Awakens,BV,"$247,966,675",12/18/2015,Jeff Tomsic,"$14,947,396,",tt2854926,12,2015,"Ed Helms, Lil Rel Howery, Jon Hamm, Annabelle ...",Comedy,"Rob McKittrick (screenplay by), Mark Steilen (..."
8,Star Wars: The Last Jedi,BV,"$220,009,584",12/15/2017,John N. Smith,"$14,931,503,",tt0112792,12,2017,"Michelle Pfeiffer, George Dzundza, Courtney B....","Biography, Drama","LouAnne Johnson (book), Ronald Bass (screenplay)"
9,Jurassic World,Uni.,"$208,806,270",6/12/2015,Rob Cohen,"$4,000,000",tt3181822,6,2015,"Jennifer Lopez, Ryan Guzman, Ian Nelson, John ...","Drama, Romance, Thriller",Barbara Curry
10,Marvel's The Avengers,BV,"$207,438,708",5/4/2012,Matthew Vaughn,"$30,000,000",tt1250777,5,2012,"Aaron Taylor-Johnson, Garrett M. Brown, Evan P...","Action, Comedy","Jane Goldman (screenplay), Matthew Vaughn (scr..."
11,Black Panther,BV,"$202,003,951",2/16/2018,Jonathan Mostow,,tt0986263,2,2018,"Bruce Willis, Radha Mitchell, Rosamund Pike, B...","Action, Crime, Mystery","Michael Ferris (screenplay), John Brancato (sc..."
12,Avengers: Age of Ultron,BV,"$191,271,109",5/1/2015,Ben Stiller,,tt0115798,5,2015,"Jim Carrey, Matthew Broderick, Leslie Mann, Ja...","Comedy, Drama, Thriller",Lou Holtz Jr.
13,Incredibles 2,BV,"$182,687,905",6/15/2018,Ron Howard,,tt3062096,6,2018,"Tom Hanks, Felicity Jones, Omar Sy, Irrfan Khan","Action, Adventure, Crime","Dan Brown (based in part on the novel by), Dav..."
14,Captain America: Civil War,BV,"$179,139,142",5/6/2016,Gabriele Muccino,,tt0814314,5,2016,"Will Smith, Rosario Dawson, Woody Harrelson, M...","Drama, Romance",Grant Nieporte
15,Beauty and the Beast (2017),BV,"$174,750,616",3/17/2017,Jason Moore,,tt1981677,3,2017,"Anna Kendrick, Skylar Astin, Ben Platt, Britta...","Comedy, Music, Romance","Kay Cannon (screenplay), Mickey Rapkin (based ..."
16,Iron Man 3,BV,"$174,144,585",5/3/2013,Michael Cuesta,,tt1961175,5,2013,"Dylan O'Brien, Charlotte Vega, Christopher Bom...","Action, Thriller","Stephen Schiff (screenplay by), Michael Finch ..."
17,Harry Potter and the Deathly Hallows Part 2,WB,"$169,189,427",7/15/2011,Joel Schumacher,,tt0117913,7,2011,"Matthew McConaughey, Sandra Bullock, Samuel L....","Crime, Drama, Thriller","John Grisham (novel), Akiva Goldsman (screenplay)"
18,Batman v Superman: Dawn of Justice,WB,"$166,007,347",3/25/2016,Patricia Riggen,,tt4257926,3,2016,"Jennifer Garner, Kylie Rogers, Martin Henderso...","Biography, Drama, Family","Christy Beam (book), Randy Brown (screenplay)"
19,The Dark Knight Rises,WB,"$160,887,295",7/20/2012,Duncan Jones,,tt0945513,7,2012,"Jake Gyllenhaal, Michelle Monaghan, Vera Farmi...","Mystery, Romance, Sci-Fi",Ben Ripley
21,The Hunger Games: Catching Fire,LGF,"$158,074,286",11/22/2013,Baz Luhrmann,,tt0455824,11,2013,"Shea Adams, Eddie Baroo, Ray Barrett, Tony Barry","Adventure, Drama, Romance","Stuart Beattie (screenplay), Baz Luhrmann (scr..."
22,Rogue One: A Star Wars Story,BV,"$155,081,681",12/16/2016,Mikael Håfström,,tt1161864,12,2016,"Anthony Hopkins, Colin O'Donoghue, Alice Braga...","Drama, Horror, Mystery","Michael Petroni, Matt Baglio (book)"
23,The Hunger Games,LGF,"$152,535,747",3/23/2012,Jodie Foster,,tt2241351,3,2012,"George Clooney, Julia Roberts, Jack O'Connell,...","Crime, Drama, Thriller","Jamie Linden (screenplay), Alan DiFiore (scree..."
25,Jurassic World: Fallen Kingdom,Uni.,"$148,024,610",6/22/2018,Paul Weiland,,tt0866439,6,2018,"Patrick Dempsey, Michelle Monaghan, Kevin McKi...","Comedy, Romance","Adam Sztykiel (screenplay), Deborah Kaplan (sc..."
26,Furious 7,Uni.,"$147,187,040",4/3/2015,Drew Goddard,,tt1259521,4,2015,"Kristen Connolly, Chris Hemsworth, Anna Hutchi...",Horror,"Joss Whedon, Drew Goddard"
27,Guardians of the Galaxy Vol. 2,BV,"$146,510,104",5/5/2017,"Danny Pang, Oxide Chun Pang",,tt0425430,5,2017,"Kristen Stewart, Dylan McDermott, Penelope Ann...","Horror, Mystery, Thriller","Mark Wheaton (screenplay), Todd Farmer (story)"
29,The Twilight Saga: Breaking Dawn Part 2,LG/S,"$141,067,634",11/16/2012,Michael Lembeck,,tt0452681,11,2012,"Tim Allen, Elizabeth Mitchell, Eric Lloyd, Jud...","Adventure, Comedy, Family","Ed Decter, John J. Strauss, Leo Benvenuti (cha..."
30,The Twilight Saga: Breaking Dawn Part 1,Sum.,"$138,122,261",11/18/2011,Michael Mann,,tt0248667,11,2011,"Will Smith, Jamie Foxx, Jon Voight, Mario Van ...","Biography, Drama, Sport","Gregory Allen Howard (story), Stephen J. Rivel..."
32,Finding Dory,BV,"$135,060,273",6/17/2016,Todd Phillips,,tt2005151,6,2016,"Miles Teller, Steve Lantz, Gregg Weiner, David...","Comedy, Crime, Drama","Stephen Chin (screenplay), Todd Phillips (scre..."
33,Suicide Squad,WB,"$133,682,248",8/5/2016,"John Francis Daley, Jonathan Goldstein",,tt1524930,8,2016,"Ed Helms, Christina Applegate, Skyler Gisondo,...","Adventure, Comedy","Jonathan Goldstein, John Francis Daley, John H..."
34,Deadpool,Fox,"$132,434,639",2/12/2016,Clint Eastwood,,tt0118548,2,2016,"Clint Eastwood, Gene Hackman, Ed Harris, Laura...","Action, Crime, Drama","David Baldacci (book), William Goldman (screen..."
35,Iron Man 2,Par.,"$128,122,480",5/7/2010,David Frankel,,tt1535438,5,2010,"Meryl Streep, Tommy Lee Jones, Steve Carell, J...","Comedy, Drama, Romance",Vanessa Taylor
36,Deadpool 2,Fox,"$125,507,153",5/18/2018,Joe Carnahan,,tt0475394,5,2018,"Ryan Reynolds, Ray Liotta, Joseph Ruskin, Alex...","Action, Crime, Drama",Joe Carnahan
37,Harry Potter and the Deathly Hallows Part 1,WB,"$125,017,372",11/19/2010,Mike Mitchell,,tt0405325,11,2010,"Michael Angarano, Kurt Russell, Kelly Preston,...","Adventure, Comedy, Family","Paul Hernandez, Robert Schooley, Mark McCorkle"
38,It,WB (NL),"$123,403,419",9/8/2017,David Bowers,,tt2023453,9,2017,"Zachary Gordon, Steve Zahn, Robert Capron, Dev...","Comedy, Family","Maya Forbes (screenplay by), Wallace Wolodarsk..."
39,Thor: Ragnarok,BV,"$122,744,989",11/3/2017,Betty Thomas,,tt0119951,11,2017,"Howard Stern, Robin Quivers, Mary McCormack, F...","Biography, Comedy, Drama","Howard Stern (book), Len Blum (screenplay), Mi..."
...,...,...,...,...,...,...,...,...,...,...,...,...
175,Outbreak,WB,"$13,420,387",3/10/1995,Wolfgang Petersen,,tt0114069,7,2017,"Dustin Hoffman, Rene Russo, Morgan Freeman, Ke...","Action, Drama, Thriller","Laurence Dworet, Robert Roy Pool"
176,Nights in Rodanthe,WB,"$13,418,454",9/26/2008,George C. Wolfe,,tt0956038,2,2010,"Richard Gere, Diane Lane, Christopher Meloni, ...","Drama, Romance","Ann Peacock (screenplay), John Romano (screenp..."
177,Stranger Than Fiction,Sony,"$13,411,093",11/10/2006,Marc Forster,,tt0420223,6,2012,"Will Ferrell, William Dick, Guy Massey, Martha...","Comedy, Drama, Fantasy",Zach Helm
178,Evolution,DW,"$13,408,351",6/8/2001,Ivan Reitman,,tt0251075,11,2014,"David Duchovny, Julianne Moore, Orlando Jones,...","Comedy, Sci-Fi","Don Jakoby (story), David Diamond (screenplay)..."
181,Superman III,WB,"$13,352,357",6/17/1983,Richard Lester,,tt0086393,10,2013,"Christopher Reeve, Richard Pryor, Jackie Coope...","Action, Comedy, Sci-Fi","Jerry Siegel (character created by: Superman),..."
182,Brooklyn's Finest,Over.,"$13,350,299",3/5/2010,"Mike Thurmeier, Galen T. Chu(co-director)",,tt3416828,6,2010,"Stephanie Beatriz, Robert Cardone, Neil deGras...","Animation, Adventure, Comedy","Michael J. Wilson (screenplay), Michael Berg (..."
183,Chappie,Sony,"$13,346,782",3/6/2015,Neill Blomkamp,,tt1823672,7,2015,"Sharlto Copley, Dev Patel, Ninja, Yo-Landi Visser","Action, Crime, Drama","Neill Blomkamp, Terri Tatchell"
185,Kick-Ass 2,Uni.,"$13,332,955",8/16/2013,Jeff Wadlow,,tt1650554,2,2015,"Aaron Taylor-Johnson, Chloë Grace Moretz, Morr...","Action, Comedy, Crime","Jeff Wadlow (screenplay), Mark Millar (comic b..."
187,Jersey Boys,WB,"$13,319,371",6/20/2014,Clint Eastwood,,tt1742044,6,2011,"Vincent Piazza, John Lloyd Young, Steve Schirr...","Biography, Drama, Music","Marshall Brickman (screenplay), Rick Elice (sc..."
191,Kiss of the Dragon,Fox,"$13,304,027",7/6/2001,Chris Nahon,,tt0271027,8,2011,"Jet Li, Bridget Fonda, Tchéky Karyo, Max Ryan","Action, Crime, Drama","Jet Li (story), Luc Besson (screenplay), Rober..."
192,Radio,SonR,"$13,303,724",10/24/2003,Michael Tollin,,tt0316465,12,2014,"Cuba Gooding Jr., Ed Harris, Alfre Woodard, S....","Biography, Drama, Sport",Mike Rich
194,Stealth,Sony,"$13,251,545",7/29/2005,Rob Cohen,,tt0382992,3,2014,"Josh Lucas, Jessica Biel, Jamie Foxx, Sam Shepard","Action, Adventure, Sci-Fi",W.D. Richter
195,Everest (2015),Uni.,"$13,242,895",9/25/2015,Peter Berg,,tt0431197,5,2012,"Jamie Foxx, Chris Cooper, Jennifer Garner, Jas...","Action, Drama, Thriller",Matthew Michael Carnahan
196,Book of Shadows: Blair Witch 2,Art.,"$13,223,887",10/27/2000,Joe Berlinger,,tt0229260,5,2015,"Kurt Loder, Chuck Scarborough, Bruce D. Reed, ...","Adventure, Fantasy, Horror","Daniel Myrick (characters), Eduardo Sánchez (c..."
198,Kiss the Girls,Par.,"$13,215,167",10/3/1997,Gary Fleder,,tt0119468,6,2012,"Morgan Freeman, Ashley Judd, Cary Elwes, Alex ...","Crime, Drama, Mystery","James Patterson (novel), David Klass (screenplay)"
199,Nim's Island,Fox,"$13,210,579",4/4/2008,Shawn Levy,,tt2692250,10,2015,"Ben Stiller, Robin Williams, Owen Wilson, Stev...","Adventure, Comedy, Family","David Guion (screenplay), Michael Handelman (s..."
202,The Age of Adaline,LGF,"$13,203,458",4/24/2015,Lee Toland Krieger,,tt1655441,6,2017,"Blake Lively, Michiel Huisman, Harrison Ford, ...","Drama, Fantasy, Romance","J. Mills Goodloe (screenplay by), Salvador Pas..."
203,Hitman,Fox,"$13,180,769",11/21/2007,Xavier Gens,,tt0465494,6,2011,"Timothy Olyphant, Dougray Scott, Olga Kurylenk...","Action, Crime, Drama",Skip Woods
204,The American,Focus,"$13,177,790",9/1/2010,Anton Corbijn,,tt1440728,7,2013,"George Clooney, Irina Björklund, Lars Hjelm, B...","Crime, Drama, Thriller","Rowan Joffe (screenplay), Martin Booth (novel)"
205,Snitch,LG/S,"$13,167,607",2/22/2013,Ric Roman Waugh,,tt0882977,2,2017,"Dwayne Johnson, Barry Pepper, Jon Bernthal, Su...","Action, Drama, Thriller","Justin Haythe, Ric Roman Waugh"
207,Crimson Peak,Uni.,"$13,143,310",10/16/2015,Guillermo del Toro,,tt2554274,10,2011,"Mia Wasikowska, Jessica Chastain, Tom Hiddlest...","Drama, Fantasy, Horror","Guillermo del Toro, Matthew Robbins"
210,The Foreigner,STX,"$13,113,024",10/13/2017,Martin Campbell,,tt1615160,3,2015,"Katie Leung, Jackie Chan, Rufus Jones, Mark Tandy","Action, Crime, Drama","David Marconi (screenplay by), Stephen Leather..."
213,Jeepers Creepers,UA,"$13,106,108",8/31/2001,Victor Salva,,tt0263488,3,2015,"Gina Philips, Justin Long, Jonathan Breck, Pat...","Horror, Mystery",Victor Salva
217,Matchstick Men,WB,"$13,087,307",9/12/2003,Ridley Scott,,tt0325805,6,2012,"Nicolas Cage, Sam Rockwell, Alison Lohman, Bru...","Comedy, Crime, Drama","Eric Garcia (book), Nicholas Griffin (screenpl..."
219,Bandits,MGM,"$13,050,700",10/12/2001,Barry Levinson,,tt0219965,11,2017,"Bruce Willis, Billy Bob Thornton, Cate Blanche...","Comedy, Crime, Drama",Harley Peyton
222,For Love of the Game,Uni.,"$13,041,685",9/17/1999,Sam Raimi,,tt0126916,7,2017,"Kevin Costner, Kelly Preston, John C. Reilly, ...","Drama, Romance, Sport","Michael Shaara (novel), Dana Stevens (screenplay)"
224,City Slickers,Col.,"$13,032,121",6/7/1991,Ron Underwood,,tt0101587,10,2010,"Billy Crystal, Daniel Stern, Bruno Kirby, Patr...",Comedy,"Lowell Ganz, Babaloo Mandel"
227,Cruel Intentions,Sony,"$13,020,565",3/5/1999,Roger Kumble,,tt0139134,4,2018,"Sarah Michelle Gellar, Ryan Phillippe, Reese W...","Drama, Romance","Choderlos de Laclos (novel), Roger Kumble (scr..."
228,The Longest Ride,Fox,"$13,019,686",4/10/2015,George Tillman Jr.,,tt2726560,3,2017,"Britt Robertson, Scott Eastwood, Alan Alda, Ja...","Drama, Romance","Nicholas Sparks (novel), Craig Bolotin (screen..."
230,Random Hearts,Sony,"$13,012,585",10/8/1999,Sydney Pollack,,tt0156934,5,2013,"Harrison Ford, Kristin Scott Thomas, Charles S...","Drama, Mystery, Romance","Warren Adler (novel), Darryl Ponicsan (adaptat..."

In [35]:
weekend_box.to_csv('after_imdb.csv')